version: '3'

vars:
  APP_NAME: "wood-hot-monitor"
  BIN_DIR: "bin"
  PACKAGE_MANAGER: "bun"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

includes:
  common: ./build/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

tasks:
  build:
    summary: Builds the application for current OS
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the built application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
