// Code generated by ent, DO NOT EDIT.

package enthotspot

import (
	"fmt"
	"wood-hot-monitor/internal/domain/hotspot"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the hotspot type in the database.
	Label = "hotspot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldIsReal holds the string denoting the is_real field in the database.
	FieldIsReal = "is_real"
	// FieldRelevance holds the string denoting the relevance field in the database.
	FieldRelevance = "relevance"
	// FieldRelevanceReason holds the string denoting the relevance_reason field in the database.
	FieldRelevanceReason = "relevance_reason"
	// FieldKeywordMentioned holds the string denoting the keyword_mentioned field in the database.
	FieldKeywordMentioned = "keyword_mentioned"
	// FieldImportance holds the string denoting the importance field in the database.
	FieldImportance = "importance"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldViewCount holds the string denoting the view_count field in the database.
	FieldViewCount = "view_count"
	// FieldLikeCount holds the string denoting the like_count field in the database.
	FieldLikeCount = "like_count"
	// FieldRetweetCount holds the string denoting the retweet_count field in the database.
	FieldRetweetCount = "retweet_count"
	// FieldReplyCount holds the string denoting the reply_count field in the database.
	FieldReplyCount = "reply_count"
	// FieldCommentCount holds the string denoting the comment_count field in the database.
	FieldCommentCount = "comment_count"
	// FieldQuoteCount holds the string denoting the quote_count field in the database.
	FieldQuoteCount = "quote_count"
	// FieldDanmakuCount holds the string denoting the danmaku_count field in the database.
	FieldDanmakuCount = "danmaku_count"
	// FieldAuthorName holds the string denoting the author_name field in the database.
	FieldAuthorName = "author_name"
	// FieldAuthorUsername holds the string denoting the author_username field in the database.
	FieldAuthorUsername = "author_username"
	// FieldAuthorAvatar holds the string denoting the author_avatar field in the database.
	FieldAuthorAvatar = "author_avatar"
	// FieldAuthorFollowers holds the string denoting the author_followers field in the database.
	FieldAuthorFollowers = "author_followers"
	// FieldAuthorVerified holds the string denoting the author_verified field in the database.
	FieldAuthorVerified = "author_verified"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldKeywordID holds the string denoting the keyword_id field in the database.
	FieldKeywordID = "keyword_id"
	// FieldIsNotified holds the string denoting the is_notified field in the database.
	FieldIsNotified = "is_notified"
	// FieldNotifiedAt holds the string denoting the notified_at field in the database.
	FieldNotifiedAt = "notified_at"
	// FieldIsRead holds the string denoting the is_read field in the database.
	FieldIsRead = "is_read"
	// EdgeKeyword holds the string denoting the keyword edge name in mutations.
	EdgeKeyword = "keyword"
	// Table holds the table name of the hotspot in the database.
	Table = "hotspots"
	// KeywordTable is the table that holds the keyword relation/edge.
	KeywordTable = "hotspots"
	// KeywordInverseTable is the table name for the Keyword entity.
	// It exists in this package in order to avoid circular dependency with the "keyword" package.
	KeywordInverseTable = "keywords"
	// KeywordColumn is the table column denoting the keyword relation/edge.
	KeywordColumn = "keyword_id"
)

// Columns holds all SQL columns for hotspot fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldContent,
	FieldURL,
	FieldSource,
	FieldSourceID,
	FieldIsReal,
	FieldRelevance,
	FieldRelevanceReason,
	FieldKeywordMentioned,
	FieldImportance,
	FieldSummary,
	FieldViewCount,
	FieldLikeCount,
	FieldRetweetCount,
	FieldReplyCount,
	FieldCommentCount,
	FieldQuoteCount,
	FieldDanmakuCount,
	FieldAuthorName,
	FieldAuthorUsername,
	FieldAuthorAvatar,
	FieldAuthorFollowers,
	FieldAuthorVerified,
	FieldPublishedAt,
	FieldCreatedAt,
	FieldKeywordID,
	FieldIsNotified,
	FieldNotifiedAt,
	FieldIsRead,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsReal holds the default value on creation for the "is_real" field.
	DefaultIsReal bool
	// DefaultRelevance holds the default value on creation for the "relevance" field.
	DefaultRelevance int
	// DefaultIsNotified holds the default value on creation for the "is_notified" field.
	DefaultIsNotified bool
	// DefaultIsRead holds the default value on creation for the "is_read" field.
	DefaultIsRead bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

const DefaultImportance hotspot.Importance = "low"

// ImportanceValidator is a validator for the "importance" field enum values. It is called by the builders before save.
func ImportanceValidator(i hotspot.Importance) error {
	switch i {
	case "low", "medium", "high", "urgent":
		return nil
	default:
		return fmt.Errorf("enthotspot: invalid enum value for importance field: %q", i)
	}
}

// OrderOption defines the ordering options for the Hotspot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByIsReal orders the results by the is_real field.
func ByIsReal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsReal, opts...).ToFunc()
}

// ByRelevance orders the results by the relevance field.
func ByRelevance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelevance, opts...).ToFunc()
}

// ByRelevanceReason orders the results by the relevance_reason field.
func ByRelevanceReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelevanceReason, opts...).ToFunc()
}

// ByKeywordMentioned orders the results by the keyword_mentioned field.
func ByKeywordMentioned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeywordMentioned, opts...).ToFunc()
}

// ByImportance orders the results by the importance field.
func ByImportance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportance, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByViewCount orders the results by the view_count field.
func ByViewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewCount, opts...).ToFunc()
}

// ByLikeCount orders the results by the like_count field.
func ByLikeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLikeCount, opts...).ToFunc()
}

// ByRetweetCount orders the results by the retweet_count field.
func ByRetweetCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetweetCount, opts...).ToFunc()
}

// ByReplyCount orders the results by the reply_count field.
func ByReplyCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyCount, opts...).ToFunc()
}

// ByCommentCount orders the results by the comment_count field.
func ByCommentCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommentCount, opts...).ToFunc()
}

// ByQuoteCount orders the results by the quote_count field.
func ByQuoteCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuoteCount, opts...).ToFunc()
}

// ByDanmakuCount orders the results by the danmaku_count field.
func ByDanmakuCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDanmakuCount, opts...).ToFunc()
}

// ByAuthorName orders the results by the author_name field.
func ByAuthorName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorName, opts...).ToFunc()
}

// ByAuthorUsername orders the results by the author_username field.
func ByAuthorUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorUsername, opts...).ToFunc()
}

// ByAuthorAvatar orders the results by the author_avatar field.
func ByAuthorAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorAvatar, opts...).ToFunc()
}

// ByAuthorFollowers orders the results by the author_followers field.
func ByAuthorFollowers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorFollowers, opts...).ToFunc()
}

// ByAuthorVerified orders the results by the author_verified field.
func ByAuthorVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorVerified, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByKeywordID orders the results by the keyword_id field.
func ByKeywordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeywordID, opts...).ToFunc()
}

// ByIsNotified orders the results by the is_notified field.
func ByIsNotified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsNotified, opts...).ToFunc()
}

// ByNotifiedAt orders the results by the notified_at field.
func ByNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifiedAt, opts...).ToFunc()
}

// ByIsRead orders the results by the is_read field.
func ByIsRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsRead, opts...).ToFunc()
}

// ByKeywordField orders the results by keyword field.
func ByKeywordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeywordStep(), sql.OrderByField(field, opts...))
	}
}
func newKeywordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeywordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, KeywordTable, KeywordColumn),
	)
}
