// Code generated by ent, DO NOT EDIT.

package hotspot

import (
	"time"
	"wood-hot-monitor/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldContent, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldURL, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldSource, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldSourceID, v))
}

// IsReal applies equality check predicate on the "is_real" field. It's identical to IsRealEQ.
func IsReal(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldIsReal, v))
}

// Relevance applies equality check predicate on the "relevance" field. It's identical to RelevanceEQ.
func Relevance(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldRelevance, v))
}

// RelevanceReason applies equality check predicate on the "relevance_reason" field. It's identical to RelevanceReasonEQ.
func RelevanceReason(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldRelevanceReason, v))
}

// KeywordMentioned applies equality check predicate on the "keyword_mentioned" field. It's identical to KeywordMentionedEQ.
func KeywordMentioned(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldKeywordMentioned, v))
}

// Importance applies equality check predicate on the "importance" field. It's identical to ImportanceEQ.
func Importance(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldImportance, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldSummary, v))
}

// ViewCount applies equality check predicate on the "view_count" field. It's identical to ViewCountEQ.
func ViewCount(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldViewCount, v))
}

// LikeCount applies equality check predicate on the "like_count" field. It's identical to LikeCountEQ.
func LikeCount(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldLikeCount, v))
}

// RetweetCount applies equality check predicate on the "retweet_count" field. It's identical to RetweetCountEQ.
func RetweetCount(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldRetweetCount, v))
}

// ReplyCount applies equality check predicate on the "reply_count" field. It's identical to ReplyCountEQ.
func ReplyCount(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldReplyCount, v))
}

// CommentCount applies equality check predicate on the "comment_count" field. It's identical to CommentCountEQ.
func CommentCount(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldCommentCount, v))
}

// QuoteCount applies equality check predicate on the "quote_count" field. It's identical to QuoteCountEQ.
func QuoteCount(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldQuoteCount, v))
}

// DanmakuCount applies equality check predicate on the "danmaku_count" field. It's identical to DanmakuCountEQ.
func DanmakuCount(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldDanmakuCount, v))
}

// AuthorName applies equality check predicate on the "author_name" field. It's identical to AuthorNameEQ.
func AuthorName(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorUsername applies equality check predicate on the "author_username" field. It's identical to AuthorUsernameEQ.
func AuthorUsername(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorUsername, v))
}

// AuthorAvatar applies equality check predicate on the "author_avatar" field. It's identical to AuthorAvatarEQ.
func AuthorAvatar(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorAvatar, v))
}

// AuthorFollowers applies equality check predicate on the "author_followers" field. It's identical to AuthorFollowersEQ.
func AuthorFollowers(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorFollowers, v))
}

// AuthorVerified applies equality check predicate on the "author_verified" field. It's identical to AuthorVerifiedEQ.
func AuthorVerified(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorVerified, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldPublishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldCreatedAt, v))
}

// KeywordID applies equality check predicate on the "keyword_id" field. It's identical to KeywordIDEQ.
func KeywordID(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldKeywordID, v))
}

// IsNotified applies equality check predicate on the "is_notified" field. It's identical to IsNotifiedEQ.
func IsNotified(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldIsNotified, v))
}

// NotifiedAt applies equality check predicate on the "notified_at" field. It's identical to NotifiedAtEQ.
func NotifiedAt(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldNotifiedAt, v))
}

// IsRead applies equality check predicate on the "is_read" field. It's identical to IsReadEQ.
func IsRead(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldIsRead, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldContent, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldURL, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldSource, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldSourceID))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldSourceID, v))
}

// IsRealEQ applies the EQ predicate on the "is_real" field.
func IsRealEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldIsReal, v))
}

// IsRealNEQ applies the NEQ predicate on the "is_real" field.
func IsRealNEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldIsReal, v))
}

// RelevanceEQ applies the EQ predicate on the "relevance" field.
func RelevanceEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldRelevance, v))
}

// RelevanceNEQ applies the NEQ predicate on the "relevance" field.
func RelevanceNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldRelevance, v))
}

// RelevanceIn applies the In predicate on the "relevance" field.
func RelevanceIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldRelevance, vs...))
}

// RelevanceNotIn applies the NotIn predicate on the "relevance" field.
func RelevanceNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldRelevance, vs...))
}

// RelevanceGT applies the GT predicate on the "relevance" field.
func RelevanceGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldRelevance, v))
}

// RelevanceGTE applies the GTE predicate on the "relevance" field.
func RelevanceGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldRelevance, v))
}

// RelevanceLT applies the LT predicate on the "relevance" field.
func RelevanceLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldRelevance, v))
}

// RelevanceLTE applies the LTE predicate on the "relevance" field.
func RelevanceLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldRelevance, v))
}

// RelevanceReasonEQ applies the EQ predicate on the "relevance_reason" field.
func RelevanceReasonEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldRelevanceReason, v))
}

// RelevanceReasonNEQ applies the NEQ predicate on the "relevance_reason" field.
func RelevanceReasonNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldRelevanceReason, v))
}

// RelevanceReasonIn applies the In predicate on the "relevance_reason" field.
func RelevanceReasonIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldRelevanceReason, vs...))
}

// RelevanceReasonNotIn applies the NotIn predicate on the "relevance_reason" field.
func RelevanceReasonNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldRelevanceReason, vs...))
}

// RelevanceReasonGT applies the GT predicate on the "relevance_reason" field.
func RelevanceReasonGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldRelevanceReason, v))
}

// RelevanceReasonGTE applies the GTE predicate on the "relevance_reason" field.
func RelevanceReasonGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldRelevanceReason, v))
}

// RelevanceReasonLT applies the LT predicate on the "relevance_reason" field.
func RelevanceReasonLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldRelevanceReason, v))
}

// RelevanceReasonLTE applies the LTE predicate on the "relevance_reason" field.
func RelevanceReasonLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldRelevanceReason, v))
}

// RelevanceReasonContains applies the Contains predicate on the "relevance_reason" field.
func RelevanceReasonContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldRelevanceReason, v))
}

// RelevanceReasonHasPrefix applies the HasPrefix predicate on the "relevance_reason" field.
func RelevanceReasonHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldRelevanceReason, v))
}

// RelevanceReasonHasSuffix applies the HasSuffix predicate on the "relevance_reason" field.
func RelevanceReasonHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldRelevanceReason, v))
}

// RelevanceReasonIsNil applies the IsNil predicate on the "relevance_reason" field.
func RelevanceReasonIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldRelevanceReason))
}

// RelevanceReasonNotNil applies the NotNil predicate on the "relevance_reason" field.
func RelevanceReasonNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldRelevanceReason))
}

// RelevanceReasonEqualFold applies the EqualFold predicate on the "relevance_reason" field.
func RelevanceReasonEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldRelevanceReason, v))
}

// RelevanceReasonContainsFold applies the ContainsFold predicate on the "relevance_reason" field.
func RelevanceReasonContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldRelevanceReason, v))
}

// KeywordMentionedEQ applies the EQ predicate on the "keyword_mentioned" field.
func KeywordMentionedEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldKeywordMentioned, v))
}

// KeywordMentionedNEQ applies the NEQ predicate on the "keyword_mentioned" field.
func KeywordMentionedNEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldKeywordMentioned, v))
}

// KeywordMentionedIsNil applies the IsNil predicate on the "keyword_mentioned" field.
func KeywordMentionedIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldKeywordMentioned))
}

// KeywordMentionedNotNil applies the NotNil predicate on the "keyword_mentioned" field.
func KeywordMentionedNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldKeywordMentioned))
}

// ImportanceEQ applies the EQ predicate on the "importance" field.
func ImportanceEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldImportance, v))
}

// ImportanceNEQ applies the NEQ predicate on the "importance" field.
func ImportanceNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldImportance, v))
}

// ImportanceIn applies the In predicate on the "importance" field.
func ImportanceIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldImportance, vs...))
}

// ImportanceNotIn applies the NotIn predicate on the "importance" field.
func ImportanceNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldImportance, vs...))
}

// ImportanceGT applies the GT predicate on the "importance" field.
func ImportanceGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldImportance, v))
}

// ImportanceGTE applies the GTE predicate on the "importance" field.
func ImportanceGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldImportance, v))
}

// ImportanceLT applies the LT predicate on the "importance" field.
func ImportanceLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldImportance, v))
}

// ImportanceLTE applies the LTE predicate on the "importance" field.
func ImportanceLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldImportance, v))
}

// ImportanceContains applies the Contains predicate on the "importance" field.
func ImportanceContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldImportance, v))
}

// ImportanceHasPrefix applies the HasPrefix predicate on the "importance" field.
func ImportanceHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldImportance, v))
}

// ImportanceHasSuffix applies the HasSuffix predicate on the "importance" field.
func ImportanceHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldImportance, v))
}

// ImportanceEqualFold applies the EqualFold predicate on the "importance" field.
func ImportanceEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldImportance, v))
}

// ImportanceContainsFold applies the ContainsFold predicate on the "importance" field.
func ImportanceContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldImportance, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldSummary, v))
}

// ViewCountEQ applies the EQ predicate on the "view_count" field.
func ViewCountEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldViewCount, v))
}

// ViewCountNEQ applies the NEQ predicate on the "view_count" field.
func ViewCountNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldViewCount, v))
}

// ViewCountIn applies the In predicate on the "view_count" field.
func ViewCountIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldViewCount, vs...))
}

// ViewCountNotIn applies the NotIn predicate on the "view_count" field.
func ViewCountNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldViewCount, vs...))
}

// ViewCountGT applies the GT predicate on the "view_count" field.
func ViewCountGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldViewCount, v))
}

// ViewCountGTE applies the GTE predicate on the "view_count" field.
func ViewCountGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldViewCount, v))
}

// ViewCountLT applies the LT predicate on the "view_count" field.
func ViewCountLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldViewCount, v))
}

// ViewCountLTE applies the LTE predicate on the "view_count" field.
func ViewCountLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldViewCount, v))
}

// ViewCountIsNil applies the IsNil predicate on the "view_count" field.
func ViewCountIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldViewCount))
}

// ViewCountNotNil applies the NotNil predicate on the "view_count" field.
func ViewCountNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldViewCount))
}

// LikeCountEQ applies the EQ predicate on the "like_count" field.
func LikeCountEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldLikeCount, v))
}

// LikeCountNEQ applies the NEQ predicate on the "like_count" field.
func LikeCountNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldLikeCount, v))
}

// LikeCountIn applies the In predicate on the "like_count" field.
func LikeCountIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldLikeCount, vs...))
}

// LikeCountNotIn applies the NotIn predicate on the "like_count" field.
func LikeCountNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldLikeCount, vs...))
}

// LikeCountGT applies the GT predicate on the "like_count" field.
func LikeCountGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldLikeCount, v))
}

// LikeCountGTE applies the GTE predicate on the "like_count" field.
func LikeCountGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldLikeCount, v))
}

// LikeCountLT applies the LT predicate on the "like_count" field.
func LikeCountLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldLikeCount, v))
}

// LikeCountLTE applies the LTE predicate on the "like_count" field.
func LikeCountLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldLikeCount, v))
}

// LikeCountIsNil applies the IsNil predicate on the "like_count" field.
func LikeCountIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldLikeCount))
}

// LikeCountNotNil applies the NotNil predicate on the "like_count" field.
func LikeCountNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldLikeCount))
}

// RetweetCountEQ applies the EQ predicate on the "retweet_count" field.
func RetweetCountEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldRetweetCount, v))
}

// RetweetCountNEQ applies the NEQ predicate on the "retweet_count" field.
func RetweetCountNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldRetweetCount, v))
}

// RetweetCountIn applies the In predicate on the "retweet_count" field.
func RetweetCountIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldRetweetCount, vs...))
}

// RetweetCountNotIn applies the NotIn predicate on the "retweet_count" field.
func RetweetCountNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldRetweetCount, vs...))
}

// RetweetCountGT applies the GT predicate on the "retweet_count" field.
func RetweetCountGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldRetweetCount, v))
}

// RetweetCountGTE applies the GTE predicate on the "retweet_count" field.
func RetweetCountGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldRetweetCount, v))
}

// RetweetCountLT applies the LT predicate on the "retweet_count" field.
func RetweetCountLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldRetweetCount, v))
}

// RetweetCountLTE applies the LTE predicate on the "retweet_count" field.
func RetweetCountLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldRetweetCount, v))
}

// RetweetCountIsNil applies the IsNil predicate on the "retweet_count" field.
func RetweetCountIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldRetweetCount))
}

// RetweetCountNotNil applies the NotNil predicate on the "retweet_count" field.
func RetweetCountNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldRetweetCount))
}

// ReplyCountEQ applies the EQ predicate on the "reply_count" field.
func ReplyCountEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldReplyCount, v))
}

// ReplyCountNEQ applies the NEQ predicate on the "reply_count" field.
func ReplyCountNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldReplyCount, v))
}

// ReplyCountIn applies the In predicate on the "reply_count" field.
func ReplyCountIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldReplyCount, vs...))
}

// ReplyCountNotIn applies the NotIn predicate on the "reply_count" field.
func ReplyCountNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldReplyCount, vs...))
}

// ReplyCountGT applies the GT predicate on the "reply_count" field.
func ReplyCountGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldReplyCount, v))
}

// ReplyCountGTE applies the GTE predicate on the "reply_count" field.
func ReplyCountGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldReplyCount, v))
}

// ReplyCountLT applies the LT predicate on the "reply_count" field.
func ReplyCountLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldReplyCount, v))
}

// ReplyCountLTE applies the LTE predicate on the "reply_count" field.
func ReplyCountLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldReplyCount, v))
}

// ReplyCountIsNil applies the IsNil predicate on the "reply_count" field.
func ReplyCountIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldReplyCount))
}

// ReplyCountNotNil applies the NotNil predicate on the "reply_count" field.
func ReplyCountNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldReplyCount))
}

// CommentCountEQ applies the EQ predicate on the "comment_count" field.
func CommentCountEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldCommentCount, v))
}

// CommentCountNEQ applies the NEQ predicate on the "comment_count" field.
func CommentCountNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldCommentCount, v))
}

// CommentCountIn applies the In predicate on the "comment_count" field.
func CommentCountIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldCommentCount, vs...))
}

// CommentCountNotIn applies the NotIn predicate on the "comment_count" field.
func CommentCountNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldCommentCount, vs...))
}

// CommentCountGT applies the GT predicate on the "comment_count" field.
func CommentCountGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldCommentCount, v))
}

// CommentCountGTE applies the GTE predicate on the "comment_count" field.
func CommentCountGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldCommentCount, v))
}

// CommentCountLT applies the LT predicate on the "comment_count" field.
func CommentCountLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldCommentCount, v))
}

// CommentCountLTE applies the LTE predicate on the "comment_count" field.
func CommentCountLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldCommentCount, v))
}

// CommentCountIsNil applies the IsNil predicate on the "comment_count" field.
func CommentCountIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldCommentCount))
}

// CommentCountNotNil applies the NotNil predicate on the "comment_count" field.
func CommentCountNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldCommentCount))
}

// QuoteCountEQ applies the EQ predicate on the "quote_count" field.
func QuoteCountEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldQuoteCount, v))
}

// QuoteCountNEQ applies the NEQ predicate on the "quote_count" field.
func QuoteCountNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldQuoteCount, v))
}

// QuoteCountIn applies the In predicate on the "quote_count" field.
func QuoteCountIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldQuoteCount, vs...))
}

// QuoteCountNotIn applies the NotIn predicate on the "quote_count" field.
func QuoteCountNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldQuoteCount, vs...))
}

// QuoteCountGT applies the GT predicate on the "quote_count" field.
func QuoteCountGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldQuoteCount, v))
}

// QuoteCountGTE applies the GTE predicate on the "quote_count" field.
func QuoteCountGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldQuoteCount, v))
}

// QuoteCountLT applies the LT predicate on the "quote_count" field.
func QuoteCountLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldQuoteCount, v))
}

// QuoteCountLTE applies the LTE predicate on the "quote_count" field.
func QuoteCountLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldQuoteCount, v))
}

// QuoteCountIsNil applies the IsNil predicate on the "quote_count" field.
func QuoteCountIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldQuoteCount))
}

// QuoteCountNotNil applies the NotNil predicate on the "quote_count" field.
func QuoteCountNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldQuoteCount))
}

// DanmakuCountEQ applies the EQ predicate on the "danmaku_count" field.
func DanmakuCountEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldDanmakuCount, v))
}

// DanmakuCountNEQ applies the NEQ predicate on the "danmaku_count" field.
func DanmakuCountNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldDanmakuCount, v))
}

// DanmakuCountIn applies the In predicate on the "danmaku_count" field.
func DanmakuCountIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldDanmakuCount, vs...))
}

// DanmakuCountNotIn applies the NotIn predicate on the "danmaku_count" field.
func DanmakuCountNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldDanmakuCount, vs...))
}

// DanmakuCountGT applies the GT predicate on the "danmaku_count" field.
func DanmakuCountGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldDanmakuCount, v))
}

// DanmakuCountGTE applies the GTE predicate on the "danmaku_count" field.
func DanmakuCountGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldDanmakuCount, v))
}

// DanmakuCountLT applies the LT predicate on the "danmaku_count" field.
func DanmakuCountLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldDanmakuCount, v))
}

// DanmakuCountLTE applies the LTE predicate on the "danmaku_count" field.
func DanmakuCountLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldDanmakuCount, v))
}

// DanmakuCountIsNil applies the IsNil predicate on the "danmaku_count" field.
func DanmakuCountIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldDanmakuCount))
}

// DanmakuCountNotNil applies the NotNil predicate on the "danmaku_count" field.
func DanmakuCountNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldDanmakuCount))
}

// AuthorNameEQ applies the EQ predicate on the "author_name" field.
func AuthorNameEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorNameNEQ applies the NEQ predicate on the "author_name" field.
func AuthorNameNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldAuthorName, v))
}

// AuthorNameIn applies the In predicate on the "author_name" field.
func AuthorNameIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldAuthorName, vs...))
}

// AuthorNameNotIn applies the NotIn predicate on the "author_name" field.
func AuthorNameNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldAuthorName, vs...))
}

// AuthorNameGT applies the GT predicate on the "author_name" field.
func AuthorNameGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldAuthorName, v))
}

// AuthorNameGTE applies the GTE predicate on the "author_name" field.
func AuthorNameGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldAuthorName, v))
}

// AuthorNameLT applies the LT predicate on the "author_name" field.
func AuthorNameLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldAuthorName, v))
}

// AuthorNameLTE applies the LTE predicate on the "author_name" field.
func AuthorNameLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldAuthorName, v))
}

// AuthorNameContains applies the Contains predicate on the "author_name" field.
func AuthorNameContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldAuthorName, v))
}

// AuthorNameHasPrefix applies the HasPrefix predicate on the "author_name" field.
func AuthorNameHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldAuthorName, v))
}

// AuthorNameHasSuffix applies the HasSuffix predicate on the "author_name" field.
func AuthorNameHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldAuthorName, v))
}

// AuthorNameIsNil applies the IsNil predicate on the "author_name" field.
func AuthorNameIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldAuthorName))
}

// AuthorNameNotNil applies the NotNil predicate on the "author_name" field.
func AuthorNameNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldAuthorName))
}

// AuthorNameEqualFold applies the EqualFold predicate on the "author_name" field.
func AuthorNameEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldAuthorName, v))
}

// AuthorNameContainsFold applies the ContainsFold predicate on the "author_name" field.
func AuthorNameContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldAuthorName, v))
}

// AuthorUsernameEQ applies the EQ predicate on the "author_username" field.
func AuthorUsernameEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorUsername, v))
}

// AuthorUsernameNEQ applies the NEQ predicate on the "author_username" field.
func AuthorUsernameNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldAuthorUsername, v))
}

// AuthorUsernameIn applies the In predicate on the "author_username" field.
func AuthorUsernameIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldAuthorUsername, vs...))
}

// AuthorUsernameNotIn applies the NotIn predicate on the "author_username" field.
func AuthorUsernameNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldAuthorUsername, vs...))
}

// AuthorUsernameGT applies the GT predicate on the "author_username" field.
func AuthorUsernameGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldAuthorUsername, v))
}

// AuthorUsernameGTE applies the GTE predicate on the "author_username" field.
func AuthorUsernameGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldAuthorUsername, v))
}

// AuthorUsernameLT applies the LT predicate on the "author_username" field.
func AuthorUsernameLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldAuthorUsername, v))
}

// AuthorUsernameLTE applies the LTE predicate on the "author_username" field.
func AuthorUsernameLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldAuthorUsername, v))
}

// AuthorUsernameContains applies the Contains predicate on the "author_username" field.
func AuthorUsernameContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldAuthorUsername, v))
}

// AuthorUsernameHasPrefix applies the HasPrefix predicate on the "author_username" field.
func AuthorUsernameHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldAuthorUsername, v))
}

// AuthorUsernameHasSuffix applies the HasSuffix predicate on the "author_username" field.
func AuthorUsernameHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldAuthorUsername, v))
}

// AuthorUsernameIsNil applies the IsNil predicate on the "author_username" field.
func AuthorUsernameIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldAuthorUsername))
}

// AuthorUsernameNotNil applies the NotNil predicate on the "author_username" field.
func AuthorUsernameNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldAuthorUsername))
}

// AuthorUsernameEqualFold applies the EqualFold predicate on the "author_username" field.
func AuthorUsernameEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldAuthorUsername, v))
}

// AuthorUsernameContainsFold applies the ContainsFold predicate on the "author_username" field.
func AuthorUsernameContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldAuthorUsername, v))
}

// AuthorAvatarEQ applies the EQ predicate on the "author_avatar" field.
func AuthorAvatarEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorAvatar, v))
}

// AuthorAvatarNEQ applies the NEQ predicate on the "author_avatar" field.
func AuthorAvatarNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldAuthorAvatar, v))
}

// AuthorAvatarIn applies the In predicate on the "author_avatar" field.
func AuthorAvatarIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldAuthorAvatar, vs...))
}

// AuthorAvatarNotIn applies the NotIn predicate on the "author_avatar" field.
func AuthorAvatarNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldAuthorAvatar, vs...))
}

// AuthorAvatarGT applies the GT predicate on the "author_avatar" field.
func AuthorAvatarGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldAuthorAvatar, v))
}

// AuthorAvatarGTE applies the GTE predicate on the "author_avatar" field.
func AuthorAvatarGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldAuthorAvatar, v))
}

// AuthorAvatarLT applies the LT predicate on the "author_avatar" field.
func AuthorAvatarLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldAuthorAvatar, v))
}

// AuthorAvatarLTE applies the LTE predicate on the "author_avatar" field.
func AuthorAvatarLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldAuthorAvatar, v))
}

// AuthorAvatarContains applies the Contains predicate on the "author_avatar" field.
func AuthorAvatarContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldAuthorAvatar, v))
}

// AuthorAvatarHasPrefix applies the HasPrefix predicate on the "author_avatar" field.
func AuthorAvatarHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldAuthorAvatar, v))
}

// AuthorAvatarHasSuffix applies the HasSuffix predicate on the "author_avatar" field.
func AuthorAvatarHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldAuthorAvatar, v))
}

// AuthorAvatarIsNil applies the IsNil predicate on the "author_avatar" field.
func AuthorAvatarIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldAuthorAvatar))
}

// AuthorAvatarNotNil applies the NotNil predicate on the "author_avatar" field.
func AuthorAvatarNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldAuthorAvatar))
}

// AuthorAvatarEqualFold applies the EqualFold predicate on the "author_avatar" field.
func AuthorAvatarEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldAuthorAvatar, v))
}

// AuthorAvatarContainsFold applies the ContainsFold predicate on the "author_avatar" field.
func AuthorAvatarContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldAuthorAvatar, v))
}

// AuthorFollowersEQ applies the EQ predicate on the "author_followers" field.
func AuthorFollowersEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorFollowers, v))
}

// AuthorFollowersNEQ applies the NEQ predicate on the "author_followers" field.
func AuthorFollowersNEQ(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldAuthorFollowers, v))
}

// AuthorFollowersIn applies the In predicate on the "author_followers" field.
func AuthorFollowersIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldAuthorFollowers, vs...))
}

// AuthorFollowersNotIn applies the NotIn predicate on the "author_followers" field.
func AuthorFollowersNotIn(vs ...int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldAuthorFollowers, vs...))
}

// AuthorFollowersGT applies the GT predicate on the "author_followers" field.
func AuthorFollowersGT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldAuthorFollowers, v))
}

// AuthorFollowersGTE applies the GTE predicate on the "author_followers" field.
func AuthorFollowersGTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldAuthorFollowers, v))
}

// AuthorFollowersLT applies the LT predicate on the "author_followers" field.
func AuthorFollowersLT(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldAuthorFollowers, v))
}

// AuthorFollowersLTE applies the LTE predicate on the "author_followers" field.
func AuthorFollowersLTE(v int) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldAuthorFollowers, v))
}

// AuthorFollowersIsNil applies the IsNil predicate on the "author_followers" field.
func AuthorFollowersIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldAuthorFollowers))
}

// AuthorFollowersNotNil applies the NotNil predicate on the "author_followers" field.
func AuthorFollowersNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldAuthorFollowers))
}

// AuthorVerifiedEQ applies the EQ predicate on the "author_verified" field.
func AuthorVerifiedEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldAuthorVerified, v))
}

// AuthorVerifiedNEQ applies the NEQ predicate on the "author_verified" field.
func AuthorVerifiedNEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldAuthorVerified, v))
}

// AuthorVerifiedIsNil applies the IsNil predicate on the "author_verified" field.
func AuthorVerifiedIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldAuthorVerified))
}

// AuthorVerifiedNotNil applies the NotNil predicate on the "author_verified" field.
func AuthorVerifiedNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldAuthorVerified))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldPublishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldCreatedAt, v))
}

// KeywordIDEQ applies the EQ predicate on the "keyword_id" field.
func KeywordIDEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldKeywordID, v))
}

// KeywordIDNEQ applies the NEQ predicate on the "keyword_id" field.
func KeywordIDNEQ(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldKeywordID, v))
}

// KeywordIDIn applies the In predicate on the "keyword_id" field.
func KeywordIDIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldKeywordID, vs...))
}

// KeywordIDNotIn applies the NotIn predicate on the "keyword_id" field.
func KeywordIDNotIn(vs ...string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldKeywordID, vs...))
}

// KeywordIDGT applies the GT predicate on the "keyword_id" field.
func KeywordIDGT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldKeywordID, v))
}

// KeywordIDGTE applies the GTE predicate on the "keyword_id" field.
func KeywordIDGTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldKeywordID, v))
}

// KeywordIDLT applies the LT predicate on the "keyword_id" field.
func KeywordIDLT(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldKeywordID, v))
}

// KeywordIDLTE applies the LTE predicate on the "keyword_id" field.
func KeywordIDLTE(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldKeywordID, v))
}

// KeywordIDContains applies the Contains predicate on the "keyword_id" field.
func KeywordIDContains(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContains(FieldKeywordID, v))
}

// KeywordIDHasPrefix applies the HasPrefix predicate on the "keyword_id" field.
func KeywordIDHasPrefix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasPrefix(FieldKeywordID, v))
}

// KeywordIDHasSuffix applies the HasSuffix predicate on the "keyword_id" field.
func KeywordIDHasSuffix(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldHasSuffix(FieldKeywordID, v))
}

// KeywordIDIsNil applies the IsNil predicate on the "keyword_id" field.
func KeywordIDIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldKeywordID))
}

// KeywordIDNotNil applies the NotNil predicate on the "keyword_id" field.
func KeywordIDNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldKeywordID))
}

// KeywordIDEqualFold applies the EqualFold predicate on the "keyword_id" field.
func KeywordIDEqualFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEqualFold(FieldKeywordID, v))
}

// KeywordIDContainsFold applies the ContainsFold predicate on the "keyword_id" field.
func KeywordIDContainsFold(v string) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldContainsFold(FieldKeywordID, v))
}

// IsNotifiedEQ applies the EQ predicate on the "is_notified" field.
func IsNotifiedEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldIsNotified, v))
}

// IsNotifiedNEQ applies the NEQ predicate on the "is_notified" field.
func IsNotifiedNEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldIsNotified, v))
}

// NotifiedAtEQ applies the EQ predicate on the "notified_at" field.
func NotifiedAtEQ(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldNotifiedAt, v))
}

// NotifiedAtNEQ applies the NEQ predicate on the "notified_at" field.
func NotifiedAtNEQ(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldNotifiedAt, v))
}

// NotifiedAtIn applies the In predicate on the "notified_at" field.
func NotifiedAtIn(vs ...time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIn(FieldNotifiedAt, vs...))
}

// NotifiedAtNotIn applies the NotIn predicate on the "notified_at" field.
func NotifiedAtNotIn(vs ...time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotIn(FieldNotifiedAt, vs...))
}

// NotifiedAtGT applies the GT predicate on the "notified_at" field.
func NotifiedAtGT(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGT(FieldNotifiedAt, v))
}

// NotifiedAtGTE applies the GTE predicate on the "notified_at" field.
func NotifiedAtGTE(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldGTE(FieldNotifiedAt, v))
}

// NotifiedAtLT applies the LT predicate on the "notified_at" field.
func NotifiedAtLT(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLT(FieldNotifiedAt, v))
}

// NotifiedAtLTE applies the LTE predicate on the "notified_at" field.
func NotifiedAtLTE(v time.Time) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldLTE(FieldNotifiedAt, v))
}

// NotifiedAtIsNil applies the IsNil predicate on the "notified_at" field.
func NotifiedAtIsNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldIsNull(FieldNotifiedAt))
}

// NotifiedAtNotNil applies the NotNil predicate on the "notified_at" field.
func NotifiedAtNotNil() predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNotNull(FieldNotifiedAt))
}

// IsReadEQ applies the EQ predicate on the "is_read" field.
func IsReadEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldEQ(FieldIsRead, v))
}

// IsReadNEQ applies the NEQ predicate on the "is_read" field.
func IsReadNEQ(v bool) predicate.Hotspot {
	return predicate.Hotspot(sql.FieldNEQ(FieldIsRead, v))
}

// HasKeyword applies the HasEdge predicate on the "keyword" edge.
func HasKeyword() predicate.Hotspot {
	return predicate.Hotspot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KeywordTable, KeywordColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeywordWith applies the HasEdge predicate on the "keyword" edge with a given conditions (other predicates).
func HasKeywordWith(preds ...predicate.Keyword) predicate.Hotspot {
	return predicate.Hotspot(func(s *sql.Selector) {
		step := newKeywordStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Hotspot) predicate.Hotspot {
	return predicate.Hotspot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Hotspot) predicate.Hotspot {
	return predicate.Hotspot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Hotspot) predicate.Hotspot {
	return predicate.Hotspot(sql.NotPredicates(p))
}
