// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HotspotsColumns holds the columns for the "hotspots" table.
	HotspotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "source", Type: field.TypeString},
		{Name: "source_id", Type: field.TypeString, Nullable: true},
		{Name: "is_real", Type: field.TypeBool, Default: true},
		{Name: "relevance", Type: field.TypeInt, Default: 0},
		{Name: "relevance_reason", Type: field.TypeString, Nullable: true},
		{Name: "keyword_mentioned", Type: field.TypeBool, Nullable: true},
		{Name: "importance", Type: field.TypeString, Default: "low"},
		{Name: "summary", Type: field.TypeString, Nullable: true},
		{Name: "view_count", Type: field.TypeInt, Nullable: true},
		{Name: "like_count", Type: field.TypeInt, Nullable: true},
		{Name: "retweet_count", Type: field.TypeInt, Nullable: true},
		{Name: "reply_count", Type: field.TypeInt, Nullable: true},
		{Name: "comment_count", Type: field.TypeInt, Nullable: true},
		{Name: "quote_count", Type: field.TypeInt, Nullable: true},
		{Name: "danmaku_count", Type: field.TypeInt, Nullable: true},
		{Name: "author_name", Type: field.TypeString, Nullable: true},
		{Name: "author_username", Type: field.TypeString, Nullable: true},
		{Name: "author_avatar", Type: field.TypeString, Nullable: true},
		{Name: "author_followers", Type: field.TypeInt, Nullable: true},
		{Name: "author_verified", Type: field.TypeBool, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"sqlite3": "datetime"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"sqlite3": "datetime"}},
		{Name: "is_notified", Type: field.TypeBool, Default: false},
		{Name: "notified_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"sqlite3": "datetime"}},
		{Name: "is_read", Type: field.TypeBool, Default: false},
		{Name: "keyword_id", Type: field.TypeString, Nullable: true},
	}
	// HotspotsTable holds the schema information for the "hotspots" table.
	HotspotsTable = &schema.Table{
		Name:       "hotspots",
		Columns:    HotspotsColumns,
		PrimaryKey: []*schema.Column{HotspotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hotspots_keywords_hotspots",
				Columns:    []*schema.Column{HotspotsColumns[29]},
				RefColumns: []*schema.Column{KeywordsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "hotspot_url_source",
				Unique:  true,
				Columns: []*schema.Column{HotspotsColumns[3], HotspotsColumns[4]},
			},
			{
				Name:    "hotspot_is_notified_is_read",
				Unique:  false,
				Columns: []*schema.Column{HotspotsColumns[26], HotspotsColumns[28]},
			},
		},
	}
	// KeywordsColumns holds the columns for the "keywords" table.
	KeywordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "text", Type: field.TypeString},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"sqlite3": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"sqlite3": "datetime"}},
	}
	// KeywordsTable holds the schema information for the "keywords" table.
	KeywordsTable = &schema.Table{
		Name:       "keywords",
		Columns:    KeywordsColumns,
		PrimaryKey: []*schema.Column{KeywordsColumns[0]},
	}
	// KeywordExpansionsColumns holds the columns for the "keyword_expansions" table.
	KeywordExpansionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "keyword", Type: field.TypeString},
		{Name: "expansion", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"sqlite3": "datetime"}},
	}
	// KeywordExpansionsTable holds the schema information for the "keyword_expansions" table.
	KeywordExpansionsTable = &schema.Table{
		Name:       "keyword_expansions",
		Columns:    KeywordExpansionsColumns,
		PrimaryKey: []*schema.Column{KeywordExpansionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "keywordexpansion_keyword",
				Unique:  false,
				Columns: []*schema.Column{KeywordExpansionsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HotspotsTable,
		KeywordsTable,
		KeywordExpansionsTable,
	}
)

func init() {
	HotspotsTable.ForeignKeys[0].RefTable = KeywordsTable
}
