// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wood-hot-monitor/ent/hotspot"
	"wood-hot-monitor/ent/keyword"
	"wood-hot-monitor/pkg/types"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HotspotCreate is the builder for creating a Hotspot entity.
type HotspotCreate struct {
	config
	mutation *HotspotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *HotspotCreate) SetTitle(v string) *HotspotCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *HotspotCreate) SetContent(v string) *HotspotCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *HotspotCreate) SetURL(v string) *HotspotCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *HotspotCreate) SetSource(v string) *HotspotCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *HotspotCreate) SetSourceID(v string) *HotspotCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableSourceID(v *string) *HotspotCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetIsReal sets the "is_real" field.
func (_c *HotspotCreate) SetIsReal(v bool) *HotspotCreate {
	_c.mutation.SetIsReal(v)
	return _c
}

// SetNillableIsReal sets the "is_real" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableIsReal(v *bool) *HotspotCreate {
	if v != nil {
		_c.SetIsReal(*v)
	}
	return _c
}

// SetRelevance sets the "relevance" field.
func (_c *HotspotCreate) SetRelevance(v int) *HotspotCreate {
	_c.mutation.SetRelevance(v)
	return _c
}

// SetNillableRelevance sets the "relevance" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableRelevance(v *int) *HotspotCreate {
	if v != nil {
		_c.SetRelevance(*v)
	}
	return _c
}

// SetRelevanceReason sets the "relevance_reason" field.
func (_c *HotspotCreate) SetRelevanceReason(v string) *HotspotCreate {
	_c.mutation.SetRelevanceReason(v)
	return _c
}

// SetNillableRelevanceReason sets the "relevance_reason" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableRelevanceReason(v *string) *HotspotCreate {
	if v != nil {
		_c.SetRelevanceReason(*v)
	}
	return _c
}

// SetKeywordMentioned sets the "keyword_mentioned" field.
func (_c *HotspotCreate) SetKeywordMentioned(v bool) *HotspotCreate {
	_c.mutation.SetKeywordMentioned(v)
	return _c
}

// SetNillableKeywordMentioned sets the "keyword_mentioned" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableKeywordMentioned(v *bool) *HotspotCreate {
	if v != nil {
		_c.SetKeywordMentioned(*v)
	}
	return _c
}

// SetImportance sets the "importance" field.
func (_c *HotspotCreate) SetImportance(v types.Importance) *HotspotCreate {
	_c.mutation.SetImportance(v)
	return _c
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableImportance(v *types.Importance) *HotspotCreate {
	if v != nil {
		_c.SetImportance(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *HotspotCreate) SetSummary(v string) *HotspotCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableSummary(v *string) *HotspotCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *HotspotCreate) SetViewCount(v int) *HotspotCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableViewCount(v *int) *HotspotCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetLikeCount sets the "like_count" field.
func (_c *HotspotCreate) SetLikeCount(v int) *HotspotCreate {
	_c.mutation.SetLikeCount(v)
	return _c
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableLikeCount(v *int) *HotspotCreate {
	if v != nil {
		_c.SetLikeCount(*v)
	}
	return _c
}

// SetRetweetCount sets the "retweet_count" field.
func (_c *HotspotCreate) SetRetweetCount(v int) *HotspotCreate {
	_c.mutation.SetRetweetCount(v)
	return _c
}

// SetNillableRetweetCount sets the "retweet_count" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableRetweetCount(v *int) *HotspotCreate {
	if v != nil {
		_c.SetRetweetCount(*v)
	}
	return _c
}

// SetReplyCount sets the "reply_count" field.
func (_c *HotspotCreate) SetReplyCount(v int) *HotspotCreate {
	_c.mutation.SetReplyCount(v)
	return _c
}

// SetNillableReplyCount sets the "reply_count" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableReplyCount(v *int) *HotspotCreate {
	if v != nil {
		_c.SetReplyCount(*v)
	}
	return _c
}

// SetCommentCount sets the "comment_count" field.
func (_c *HotspotCreate) SetCommentCount(v int) *HotspotCreate {
	_c.mutation.SetCommentCount(v)
	return _c
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableCommentCount(v *int) *HotspotCreate {
	if v != nil {
		_c.SetCommentCount(*v)
	}
	return _c
}

// SetQuoteCount sets the "quote_count" field.
func (_c *HotspotCreate) SetQuoteCount(v int) *HotspotCreate {
	_c.mutation.SetQuoteCount(v)
	return _c
}

// SetNillableQuoteCount sets the "quote_count" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableQuoteCount(v *int) *HotspotCreate {
	if v != nil {
		_c.SetQuoteCount(*v)
	}
	return _c
}

// SetDanmakuCount sets the "danmaku_count" field.
func (_c *HotspotCreate) SetDanmakuCount(v int) *HotspotCreate {
	_c.mutation.SetDanmakuCount(v)
	return _c
}

// SetNillableDanmakuCount sets the "danmaku_count" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableDanmakuCount(v *int) *HotspotCreate {
	if v != nil {
		_c.SetDanmakuCount(*v)
	}
	return _c
}

// SetAuthorName sets the "author_name" field.
func (_c *HotspotCreate) SetAuthorName(v string) *HotspotCreate {
	_c.mutation.SetAuthorName(v)
	return _c
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableAuthorName(v *string) *HotspotCreate {
	if v != nil {
		_c.SetAuthorName(*v)
	}
	return _c
}

// SetAuthorUsername sets the "author_username" field.
func (_c *HotspotCreate) SetAuthorUsername(v string) *HotspotCreate {
	_c.mutation.SetAuthorUsername(v)
	return _c
}

// SetNillableAuthorUsername sets the "author_username" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableAuthorUsername(v *string) *HotspotCreate {
	if v != nil {
		_c.SetAuthorUsername(*v)
	}
	return _c
}

// SetAuthorAvatar sets the "author_avatar" field.
func (_c *HotspotCreate) SetAuthorAvatar(v string) *HotspotCreate {
	_c.mutation.SetAuthorAvatar(v)
	return _c
}

// SetNillableAuthorAvatar sets the "author_avatar" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableAuthorAvatar(v *string) *HotspotCreate {
	if v != nil {
		_c.SetAuthorAvatar(*v)
	}
	return _c
}

// SetAuthorFollowers sets the "author_followers" field.
func (_c *HotspotCreate) SetAuthorFollowers(v int) *HotspotCreate {
	_c.mutation.SetAuthorFollowers(v)
	return _c
}

// SetNillableAuthorFollowers sets the "author_followers" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableAuthorFollowers(v *int) *HotspotCreate {
	if v != nil {
		_c.SetAuthorFollowers(*v)
	}
	return _c
}

// SetAuthorVerified sets the "author_verified" field.
func (_c *HotspotCreate) SetAuthorVerified(v bool) *HotspotCreate {
	_c.mutation.SetAuthorVerified(v)
	return _c
}

// SetNillableAuthorVerified sets the "author_verified" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableAuthorVerified(v *bool) *HotspotCreate {
	if v != nil {
		_c.SetAuthorVerified(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *HotspotCreate) SetPublishedAt(v time.Time) *HotspotCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *HotspotCreate) SetNillablePublishedAt(v *time.Time) *HotspotCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HotspotCreate) SetCreatedAt(v time.Time) *HotspotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetKeywordID sets the "keyword_id" field.
func (_c *HotspotCreate) SetKeywordID(v string) *HotspotCreate {
	_c.mutation.SetKeywordID(v)
	return _c
}

// SetNillableKeywordID sets the "keyword_id" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableKeywordID(v *string) *HotspotCreate {
	if v != nil {
		_c.SetKeywordID(*v)
	}
	return _c
}

// SetIsNotified sets the "is_notified" field.
func (_c *HotspotCreate) SetIsNotified(v bool) *HotspotCreate {
	_c.mutation.SetIsNotified(v)
	return _c
}

// SetNillableIsNotified sets the "is_notified" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableIsNotified(v *bool) *HotspotCreate {
	if v != nil {
		_c.SetIsNotified(*v)
	}
	return _c
}

// SetNotifiedAt sets the "notified_at" field.
func (_c *HotspotCreate) SetNotifiedAt(v time.Time) *HotspotCreate {
	_c.mutation.SetNotifiedAt(v)
	return _c
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableNotifiedAt(v *time.Time) *HotspotCreate {
	if v != nil {
		_c.SetNotifiedAt(*v)
	}
	return _c
}

// SetIsRead sets the "is_read" field.
func (_c *HotspotCreate) SetIsRead(v bool) *HotspotCreate {
	_c.mutation.SetIsRead(v)
	return _c
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableIsRead(v *bool) *HotspotCreate {
	if v != nil {
		_c.SetIsRead(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HotspotCreate) SetID(v string) *HotspotCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *HotspotCreate) SetNillableID(v *string) *HotspotCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetKeyword sets the "keyword" edge to the Keyword entity.
func (_c *HotspotCreate) SetKeyword(v *Keyword) *HotspotCreate {
	return _c.SetKeywordID(v.ID)
}

// Mutation returns the HotspotMutation object of the builder.
func (_c *HotspotCreate) Mutation() *HotspotMutation {
	return _c.mutation
}

// Save creates the Hotspot in the database.
func (_c *HotspotCreate) Save(ctx context.Context) (*Hotspot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HotspotCreate) SaveX(ctx context.Context) *Hotspot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HotspotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HotspotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HotspotCreate) defaults() {
	if _, ok := _c.mutation.IsReal(); !ok {
		v := hotspot.DefaultIsReal
		_c.mutation.SetIsReal(v)
	}
	if _, ok := _c.mutation.Relevance(); !ok {
		v := hotspot.DefaultRelevance
		_c.mutation.SetRelevance(v)
	}
	if _, ok := _c.mutation.Importance(); !ok {
		v := hotspot.DefaultImportance
		_c.mutation.SetImportance(v)
	}
	if _, ok := _c.mutation.IsNotified(); !ok {
		v := hotspot.DefaultIsNotified
		_c.mutation.SetIsNotified(v)
	}
	if _, ok := _c.mutation.IsRead(); !ok {
		v := hotspot.DefaultIsRead
		_c.mutation.SetIsRead(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := hotspot.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HotspotCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Hotspot.title"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Hotspot.content"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Hotspot.url"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Hotspot.source"`)}
	}
	if _, ok := _c.mutation.IsReal(); !ok {
		return &ValidationError{Name: "is_real", err: errors.New(`ent: missing required field "Hotspot.is_real"`)}
	}
	if _, ok := _c.mutation.Relevance(); !ok {
		return &ValidationError{Name: "relevance", err: errors.New(`ent: missing required field "Hotspot.relevance"`)}
	}
	if _, ok := _c.mutation.Importance(); !ok {
		return &ValidationError{Name: "importance", err: errors.New(`ent: missing required field "Hotspot.importance"`)}
	}
	if v, ok := _c.mutation.Importance(); ok {
		if err := hotspot.ImportanceValidator(v); err != nil {
			return &ValidationError{Name: "importance", err: fmt.Errorf(`ent: validator failed for field "Hotspot.importance": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Hotspot.created_at"`)}
	}
	if _, ok := _c.mutation.IsNotified(); !ok {
		return &ValidationError{Name: "is_notified", err: errors.New(`ent: missing required field "Hotspot.is_notified"`)}
	}
	if _, ok := _c.mutation.IsRead(); !ok {
		return &ValidationError{Name: "is_read", err: errors.New(`ent: missing required field "Hotspot.is_read"`)}
	}
	return nil
}

func (_c *HotspotCreate) sqlSave(ctx context.Context) (*Hotspot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Hotspot.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HotspotCreate) createSpec() (*Hotspot, *sqlgraph.CreateSpec) {
	var (
		_node = &Hotspot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hotspot.Table, sqlgraph.NewFieldSpec(hotspot.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(hotspot.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(hotspot.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(hotspot.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(hotspot.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(hotspot.FieldSourceID, field.TypeString, value)
		_node.SourceID = &value
	}
	if value, ok := _c.mutation.IsReal(); ok {
		_spec.SetField(hotspot.FieldIsReal, field.TypeBool, value)
		_node.IsReal = value
	}
	if value, ok := _c.mutation.Relevance(); ok {
		_spec.SetField(hotspot.FieldRelevance, field.TypeInt, value)
		_node.Relevance = value
	}
	if value, ok := _c.mutation.RelevanceReason(); ok {
		_spec.SetField(hotspot.FieldRelevanceReason, field.TypeString, value)
		_node.RelevanceReason = &value
	}
	if value, ok := _c.mutation.KeywordMentioned(); ok {
		_spec.SetField(hotspot.FieldKeywordMentioned, field.TypeBool, value)
		_node.KeywordMentioned = &value
	}
	if value, ok := _c.mutation.Importance(); ok {
		_spec.SetField(hotspot.FieldImportance, field.TypeEnum, value)
		_node.Importance = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(hotspot.FieldSummary, field.TypeString, value)
		_node.Summary = &value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(hotspot.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = &value
	}
	if value, ok := _c.mutation.LikeCount(); ok {
		_spec.SetField(hotspot.FieldLikeCount, field.TypeInt, value)
		_node.LikeCount = &value
	}
	if value, ok := _c.mutation.RetweetCount(); ok {
		_spec.SetField(hotspot.FieldRetweetCount, field.TypeInt, value)
		_node.RetweetCount = &value
	}
	if value, ok := _c.mutation.ReplyCount(); ok {
		_spec.SetField(hotspot.FieldReplyCount, field.TypeInt, value)
		_node.ReplyCount = &value
	}
	if value, ok := _c.mutation.CommentCount(); ok {
		_spec.SetField(hotspot.FieldCommentCount, field.TypeInt, value)
		_node.CommentCount = &value
	}
	if value, ok := _c.mutation.QuoteCount(); ok {
		_spec.SetField(hotspot.FieldQuoteCount, field.TypeInt, value)
		_node.QuoteCount = &value
	}
	if value, ok := _c.mutation.DanmakuCount(); ok {
		_spec.SetField(hotspot.FieldDanmakuCount, field.TypeInt, value)
		_node.DanmakuCount = &value
	}
	if value, ok := _c.mutation.AuthorName(); ok {
		_spec.SetField(hotspot.FieldAuthorName, field.TypeString, value)
		_node.AuthorName = &value
	}
	if value, ok := _c.mutation.AuthorUsername(); ok {
		_spec.SetField(hotspot.FieldAuthorUsername, field.TypeString, value)
		_node.AuthorUsername = &value
	}
	if value, ok := _c.mutation.AuthorAvatar(); ok {
		_spec.SetField(hotspot.FieldAuthorAvatar, field.TypeString, value)
		_node.AuthorAvatar = &value
	}
	if value, ok := _c.mutation.AuthorFollowers(); ok {
		_spec.SetField(hotspot.FieldAuthorFollowers, field.TypeInt, value)
		_node.AuthorFollowers = &value
	}
	if value, ok := _c.mutation.AuthorVerified(); ok {
		_spec.SetField(hotspot.FieldAuthorVerified, field.TypeBool, value)
		_node.AuthorVerified = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(hotspot.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hotspot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.IsNotified(); ok {
		_spec.SetField(hotspot.FieldIsNotified, field.TypeBool, value)
		_node.IsNotified = value
	}
	if value, ok := _c.mutation.NotifiedAt(); ok {
		_spec.SetField(hotspot.FieldNotifiedAt, field.TypeTime, value)
		_node.NotifiedAt = &value
	}
	if value, ok := _c.mutation.IsRead(); ok {
		_spec.SetField(hotspot.FieldIsRead, field.TypeBool, value)
		_node.IsRead = value
	}
	if nodes := _c.mutation.KeywordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hotspot.KeywordTable,
			Columns: []string{hotspot.KeywordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.KeywordID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Hotspot.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HotspotUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *HotspotCreate) OnConflict(opts ...sql.ConflictOption) *HotspotUpsertOne {
	_c.conflict = opts
	return &HotspotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Hotspot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HotspotCreate) OnConflictColumns(columns ...string) *HotspotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HotspotUpsertOne{
		create: _c,
	}
}

type (
	// HotspotUpsertOne is the builder for "upsert"-ing
	//  one Hotspot node.
	HotspotUpsertOne struct {
		create *HotspotCreate
	}

	// HotspotUpsert is the "OnConflict" setter.
	HotspotUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *HotspotUpsert) SetTitle(v string) *HotspotUpsert {
	u.Set(hotspot.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateTitle() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *HotspotUpsert) SetContent(v string) *HotspotUpsert {
	u.Set(hotspot.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateContent() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldContent)
	return u
}

// SetURL sets the "url" field.
func (u *HotspotUpsert) SetURL(v string) *HotspotUpsert {
	u.Set(hotspot.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateURL() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldURL)
	return u
}

// SetSource sets the "source" field.
func (u *HotspotUpsert) SetSource(v string) *HotspotUpsert {
	u.Set(hotspot.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateSource() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldSource)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *HotspotUpsert) SetSourceID(v string) *HotspotUpsert {
	u.Set(hotspot.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateSourceID() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldSourceID)
	return u
}

// ClearSourceID clears the value of the "source_id" field.
func (u *HotspotUpsert) ClearSourceID() *HotspotUpsert {
	u.SetNull(hotspot.FieldSourceID)
	return u
}

// SetIsReal sets the "is_real" field.
func (u *HotspotUpsert) SetIsReal(v bool) *HotspotUpsert {
	u.Set(hotspot.FieldIsReal, v)
	return u
}

// UpdateIsReal sets the "is_real" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateIsReal() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldIsReal)
	return u
}

// SetRelevance sets the "relevance" field.
func (u *HotspotUpsert) SetRelevance(v int) *HotspotUpsert {
	u.Set(hotspot.FieldRelevance, v)
	return u
}

// UpdateRelevance sets the "relevance" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateRelevance() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldRelevance)
	return u
}

// AddRelevance adds v to the "relevance" field.
func (u *HotspotUpsert) AddRelevance(v int) *HotspotUpsert {
	u.Add(hotspot.FieldRelevance, v)
	return u
}

// SetRelevanceReason sets the "relevance_reason" field.
func (u *HotspotUpsert) SetRelevanceReason(v string) *HotspotUpsert {
	u.Set(hotspot.FieldRelevanceReason, v)
	return u
}

// UpdateRelevanceReason sets the "relevance_reason" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateRelevanceReason() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldRelevanceReason)
	return u
}

// ClearRelevanceReason clears the value of the "relevance_reason" field.
func (u *HotspotUpsert) ClearRelevanceReason() *HotspotUpsert {
	u.SetNull(hotspot.FieldRelevanceReason)
	return u
}

// SetKeywordMentioned sets the "keyword_mentioned" field.
func (u *HotspotUpsert) SetKeywordMentioned(v bool) *HotspotUpsert {
	u.Set(hotspot.FieldKeywordMentioned, v)
	return u
}

// UpdateKeywordMentioned sets the "keyword_mentioned" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateKeywordMentioned() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldKeywordMentioned)
	return u
}

// ClearKeywordMentioned clears the value of the "keyword_mentioned" field.
func (u *HotspotUpsert) ClearKeywordMentioned() *HotspotUpsert {
	u.SetNull(hotspot.FieldKeywordMentioned)
	return u
}

// SetImportance sets the "importance" field.
func (u *HotspotUpsert) SetImportance(v types.Importance) *HotspotUpsert {
	u.Set(hotspot.FieldImportance, v)
	return u
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateImportance() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldImportance)
	return u
}

// SetSummary sets the "summary" field.
func (u *HotspotUpsert) SetSummary(v string) *HotspotUpsert {
	u.Set(hotspot.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateSummary() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldSummary)
	return u
}

// ClearSummary clears the value of the "summary" field.
func (u *HotspotUpsert) ClearSummary() *HotspotUpsert {
	u.SetNull(hotspot.FieldSummary)
	return u
}

// SetViewCount sets the "view_count" field.
func (u *HotspotUpsert) SetViewCount(v int) *HotspotUpsert {
	u.Set(hotspot.FieldViewCount, v)
	return u
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateViewCount() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldViewCount)
	return u
}

// AddViewCount adds v to the "view_count" field.
func (u *HotspotUpsert) AddViewCount(v int) *HotspotUpsert {
	u.Add(hotspot.FieldViewCount, v)
	return u
}

// ClearViewCount clears the value of the "view_count" field.
func (u *HotspotUpsert) ClearViewCount() *HotspotUpsert {
	u.SetNull(hotspot.FieldViewCount)
	return u
}

// SetLikeCount sets the "like_count" field.
func (u *HotspotUpsert) SetLikeCount(v int) *HotspotUpsert {
	u.Set(hotspot.FieldLikeCount, v)
	return u
}

// UpdateLikeCount sets the "like_count" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateLikeCount() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldLikeCount)
	return u
}

// AddLikeCount adds v to the "like_count" field.
func (u *HotspotUpsert) AddLikeCount(v int) *HotspotUpsert {
	u.Add(hotspot.FieldLikeCount, v)
	return u
}

// ClearLikeCount clears the value of the "like_count" field.
func (u *HotspotUpsert) ClearLikeCount() *HotspotUpsert {
	u.SetNull(hotspot.FieldLikeCount)
	return u
}

// SetRetweetCount sets the "retweet_count" field.
func (u *HotspotUpsert) SetRetweetCount(v int) *HotspotUpsert {
	u.Set(hotspot.FieldRetweetCount, v)
	return u
}

// UpdateRetweetCount sets the "retweet_count" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateRetweetCount() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldRetweetCount)
	return u
}

// AddRetweetCount adds v to the "retweet_count" field.
func (u *HotspotUpsert) AddRetweetCount(v int) *HotspotUpsert {
	u.Add(hotspot.FieldRetweetCount, v)
	return u
}

// ClearRetweetCount clears the value of the "retweet_count" field.
func (u *HotspotUpsert) ClearRetweetCount() *HotspotUpsert {
	u.SetNull(hotspot.FieldRetweetCount)
	return u
}

// SetReplyCount sets the "reply_count" field.
func (u *HotspotUpsert) SetReplyCount(v int) *HotspotUpsert {
	u.Set(hotspot.FieldReplyCount, v)
	return u
}

// UpdateReplyCount sets the "reply_count" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateReplyCount() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldReplyCount)
	return u
}

// AddReplyCount adds v to the "reply_count" field.
func (u *HotspotUpsert) AddReplyCount(v int) *HotspotUpsert {
	u.Add(hotspot.FieldReplyCount, v)
	return u
}

// ClearReplyCount clears the value of the "reply_count" field.
func (u *HotspotUpsert) ClearReplyCount() *HotspotUpsert {
	u.SetNull(hotspot.FieldReplyCount)
	return u
}

// SetCommentCount sets the "comment_count" field.
func (u *HotspotUpsert) SetCommentCount(v int) *HotspotUpsert {
	u.Set(hotspot.FieldCommentCount, v)
	return u
}

// UpdateCommentCount sets the "comment_count" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateCommentCount() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldCommentCount)
	return u
}

// AddCommentCount adds v to the "comment_count" field.
func (u *HotspotUpsert) AddCommentCount(v int) *HotspotUpsert {
	u.Add(hotspot.FieldCommentCount, v)
	return u
}

// ClearCommentCount clears the value of the "comment_count" field.
func (u *HotspotUpsert) ClearCommentCount() *HotspotUpsert {
	u.SetNull(hotspot.FieldCommentCount)
	return u
}

// SetQuoteCount sets the "quote_count" field.
func (u *HotspotUpsert) SetQuoteCount(v int) *HotspotUpsert {
	u.Set(hotspot.FieldQuoteCount, v)
	return u
}

// UpdateQuoteCount sets the "quote_count" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateQuoteCount() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldQuoteCount)
	return u
}

// AddQuoteCount adds v to the "quote_count" field.
func (u *HotspotUpsert) AddQuoteCount(v int) *HotspotUpsert {
	u.Add(hotspot.FieldQuoteCount, v)
	return u
}

// ClearQuoteCount clears the value of the "quote_count" field.
func (u *HotspotUpsert) ClearQuoteCount() *HotspotUpsert {
	u.SetNull(hotspot.FieldQuoteCount)
	return u
}

// SetDanmakuCount sets the "danmaku_count" field.
func (u *HotspotUpsert) SetDanmakuCount(v int) *HotspotUpsert {
	u.Set(hotspot.FieldDanmakuCount, v)
	return u
}

// UpdateDanmakuCount sets the "danmaku_count" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateDanmakuCount() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldDanmakuCount)
	return u
}

// AddDanmakuCount adds v to the "danmaku_count" field.
func (u *HotspotUpsert) AddDanmakuCount(v int) *HotspotUpsert {
	u.Add(hotspot.FieldDanmakuCount, v)
	return u
}

// ClearDanmakuCount clears the value of the "danmaku_count" field.
func (u *HotspotUpsert) ClearDanmakuCount() *HotspotUpsert {
	u.SetNull(hotspot.FieldDanmakuCount)
	return u
}

// SetAuthorName sets the "author_name" field.
func (u *HotspotUpsert) SetAuthorName(v string) *HotspotUpsert {
	u.Set(hotspot.FieldAuthorName, v)
	return u
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateAuthorName() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldAuthorName)
	return u
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *HotspotUpsert) ClearAuthorName() *HotspotUpsert {
	u.SetNull(hotspot.FieldAuthorName)
	return u
}

// SetAuthorUsername sets the "author_username" field.
func (u *HotspotUpsert) SetAuthorUsername(v string) *HotspotUpsert {
	u.Set(hotspot.FieldAuthorUsername, v)
	return u
}

// UpdateAuthorUsername sets the "author_username" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateAuthorUsername() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldAuthorUsername)
	return u
}

// ClearAuthorUsername clears the value of the "author_username" field.
func (u *HotspotUpsert) ClearAuthorUsername() *HotspotUpsert {
	u.SetNull(hotspot.FieldAuthorUsername)
	return u
}

// SetAuthorAvatar sets the "author_avatar" field.
func (u *HotspotUpsert) SetAuthorAvatar(v string) *HotspotUpsert {
	u.Set(hotspot.FieldAuthorAvatar, v)
	return u
}

// UpdateAuthorAvatar sets the "author_avatar" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateAuthorAvatar() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldAuthorAvatar)
	return u
}

// ClearAuthorAvatar clears the value of the "author_avatar" field.
func (u *HotspotUpsert) ClearAuthorAvatar() *HotspotUpsert {
	u.SetNull(hotspot.FieldAuthorAvatar)
	return u
}

// SetAuthorFollowers sets the "author_followers" field.
func (u *HotspotUpsert) SetAuthorFollowers(v int) *HotspotUpsert {
	u.Set(hotspot.FieldAuthorFollowers, v)
	return u
}

// UpdateAuthorFollowers sets the "author_followers" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateAuthorFollowers() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldAuthorFollowers)
	return u
}

// AddAuthorFollowers adds v to the "author_followers" field.
func (u *HotspotUpsert) AddAuthorFollowers(v int) *HotspotUpsert {
	u.Add(hotspot.FieldAuthorFollowers, v)
	return u
}

// ClearAuthorFollowers clears the value of the "author_followers" field.
func (u *HotspotUpsert) ClearAuthorFollowers() *HotspotUpsert {
	u.SetNull(hotspot.FieldAuthorFollowers)
	return u
}

// SetAuthorVerified sets the "author_verified" field.
func (u *HotspotUpsert) SetAuthorVerified(v bool) *HotspotUpsert {
	u.Set(hotspot.FieldAuthorVerified, v)
	return u
}

// UpdateAuthorVerified sets the "author_verified" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateAuthorVerified() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldAuthorVerified)
	return u
}

// ClearAuthorVerified clears the value of the "author_verified" field.
func (u *HotspotUpsert) ClearAuthorVerified() *HotspotUpsert {
	u.SetNull(hotspot.FieldAuthorVerified)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *HotspotUpsert) SetPublishedAt(v time.Time) *HotspotUpsert {
	u.Set(hotspot.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *HotspotUpsert) UpdatePublishedAt() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *HotspotUpsert) ClearPublishedAt() *HotspotUpsert {
	u.SetNull(hotspot.FieldPublishedAt)
	return u
}

// SetKeywordID sets the "keyword_id" field.
func (u *HotspotUpsert) SetKeywordID(v string) *HotspotUpsert {
	u.Set(hotspot.FieldKeywordID, v)
	return u
}

// UpdateKeywordID sets the "keyword_id" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateKeywordID() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldKeywordID)
	return u
}

// ClearKeywordID clears the value of the "keyword_id" field.
func (u *HotspotUpsert) ClearKeywordID() *HotspotUpsert {
	u.SetNull(hotspot.FieldKeywordID)
	return u
}

// SetIsNotified sets the "is_notified" field.
func (u *HotspotUpsert) SetIsNotified(v bool) *HotspotUpsert {
	u.Set(hotspot.FieldIsNotified, v)
	return u
}

// UpdateIsNotified sets the "is_notified" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateIsNotified() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldIsNotified)
	return u
}

// SetNotifiedAt sets the "notified_at" field.
func (u *HotspotUpsert) SetNotifiedAt(v time.Time) *HotspotUpsert {
	u.Set(hotspot.FieldNotifiedAt, v)
	return u
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateNotifiedAt() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldNotifiedAt)
	return u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *HotspotUpsert) ClearNotifiedAt() *HotspotUpsert {
	u.SetNull(hotspot.FieldNotifiedAt)
	return u
}

// SetIsRead sets the "is_read" field.
func (u *HotspotUpsert) SetIsRead(v bool) *HotspotUpsert {
	u.Set(hotspot.FieldIsRead, v)
	return u
}

// UpdateIsRead sets the "is_read" field to the value that was provided on create.
func (u *HotspotUpsert) UpdateIsRead() *HotspotUpsert {
	u.SetExcluded(hotspot.FieldIsRead)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Hotspot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(hotspot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HotspotUpsertOne) UpdateNewValues() *HotspotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(hotspot.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(hotspot.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Hotspot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HotspotUpsertOne) Ignore() *HotspotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HotspotUpsertOne) DoNothing() *HotspotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HotspotCreate.OnConflict
// documentation for more info.
func (u *HotspotUpsertOne) Update(set func(*HotspotUpsert)) *HotspotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HotspotUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *HotspotUpsertOne) SetTitle(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateTitle() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *HotspotUpsertOne) SetContent(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateContent() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateContent()
	})
}

// SetURL sets the "url" field.
func (u *HotspotUpsertOne) SetURL(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateURL() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateURL()
	})
}

// SetSource sets the "source" field.
func (u *HotspotUpsertOne) SetSource(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateSource() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateSource()
	})
}

// SetSourceID sets the "source_id" field.
func (u *HotspotUpsertOne) SetSourceID(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateSourceID() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateSourceID()
	})
}

// ClearSourceID clears the value of the "source_id" field.
func (u *HotspotUpsertOne) ClearSourceID() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearSourceID()
	})
}

// SetIsReal sets the "is_real" field.
func (u *HotspotUpsertOne) SetIsReal(v bool) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetIsReal(v)
	})
}

// UpdateIsReal sets the "is_real" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateIsReal() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateIsReal()
	})
}

// SetRelevance sets the "relevance" field.
func (u *HotspotUpsertOne) SetRelevance(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetRelevance(v)
	})
}

// AddRelevance adds v to the "relevance" field.
func (u *HotspotUpsertOne) AddRelevance(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddRelevance(v)
	})
}

// UpdateRelevance sets the "relevance" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateRelevance() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateRelevance()
	})
}

// SetRelevanceReason sets the "relevance_reason" field.
func (u *HotspotUpsertOne) SetRelevanceReason(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetRelevanceReason(v)
	})
}

// UpdateRelevanceReason sets the "relevance_reason" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateRelevanceReason() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateRelevanceReason()
	})
}

// ClearRelevanceReason clears the value of the "relevance_reason" field.
func (u *HotspotUpsertOne) ClearRelevanceReason() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearRelevanceReason()
	})
}

// SetKeywordMentioned sets the "keyword_mentioned" field.
func (u *HotspotUpsertOne) SetKeywordMentioned(v bool) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetKeywordMentioned(v)
	})
}

// UpdateKeywordMentioned sets the "keyword_mentioned" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateKeywordMentioned() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateKeywordMentioned()
	})
}

// ClearKeywordMentioned clears the value of the "keyword_mentioned" field.
func (u *HotspotUpsertOne) ClearKeywordMentioned() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearKeywordMentioned()
	})
}

// SetImportance sets the "importance" field.
func (u *HotspotUpsertOne) SetImportance(v types.Importance) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetImportance(v)
	})
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateImportance() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateImportance()
	})
}

// SetSummary sets the "summary" field.
func (u *HotspotUpsertOne) SetSummary(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateSummary() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *HotspotUpsertOne) ClearSummary() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearSummary()
	})
}

// SetViewCount sets the "view_count" field.
func (u *HotspotUpsertOne) SetViewCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *HotspotUpsertOne) AddViewCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateViewCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateViewCount()
	})
}

// ClearViewCount clears the value of the "view_count" field.
func (u *HotspotUpsertOne) ClearViewCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearViewCount()
	})
}

// SetLikeCount sets the "like_count" field.
func (u *HotspotUpsertOne) SetLikeCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetLikeCount(v)
	})
}

// AddLikeCount adds v to the "like_count" field.
func (u *HotspotUpsertOne) AddLikeCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddLikeCount(v)
	})
}

// UpdateLikeCount sets the "like_count" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateLikeCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateLikeCount()
	})
}

// ClearLikeCount clears the value of the "like_count" field.
func (u *HotspotUpsertOne) ClearLikeCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearLikeCount()
	})
}

// SetRetweetCount sets the "retweet_count" field.
func (u *HotspotUpsertOne) SetRetweetCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetRetweetCount(v)
	})
}

// AddRetweetCount adds v to the "retweet_count" field.
func (u *HotspotUpsertOne) AddRetweetCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddRetweetCount(v)
	})
}

// UpdateRetweetCount sets the "retweet_count" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateRetweetCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateRetweetCount()
	})
}

// ClearRetweetCount clears the value of the "retweet_count" field.
func (u *HotspotUpsertOne) ClearRetweetCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearRetweetCount()
	})
}

// SetReplyCount sets the "reply_count" field.
func (u *HotspotUpsertOne) SetReplyCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetReplyCount(v)
	})
}

// AddReplyCount adds v to the "reply_count" field.
func (u *HotspotUpsertOne) AddReplyCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddReplyCount(v)
	})
}

// UpdateReplyCount sets the "reply_count" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateReplyCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateReplyCount()
	})
}

// ClearReplyCount clears the value of the "reply_count" field.
func (u *HotspotUpsertOne) ClearReplyCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearReplyCount()
	})
}

// SetCommentCount sets the "comment_count" field.
func (u *HotspotUpsertOne) SetCommentCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetCommentCount(v)
	})
}

// AddCommentCount adds v to the "comment_count" field.
func (u *HotspotUpsertOne) AddCommentCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddCommentCount(v)
	})
}

// UpdateCommentCount sets the "comment_count" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateCommentCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateCommentCount()
	})
}

// ClearCommentCount clears the value of the "comment_count" field.
func (u *HotspotUpsertOne) ClearCommentCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearCommentCount()
	})
}

// SetQuoteCount sets the "quote_count" field.
func (u *HotspotUpsertOne) SetQuoteCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetQuoteCount(v)
	})
}

// AddQuoteCount adds v to the "quote_count" field.
func (u *HotspotUpsertOne) AddQuoteCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddQuoteCount(v)
	})
}

// UpdateQuoteCount sets the "quote_count" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateQuoteCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateQuoteCount()
	})
}

// ClearQuoteCount clears the value of the "quote_count" field.
func (u *HotspotUpsertOne) ClearQuoteCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearQuoteCount()
	})
}

// SetDanmakuCount sets the "danmaku_count" field.
func (u *HotspotUpsertOne) SetDanmakuCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetDanmakuCount(v)
	})
}

// AddDanmakuCount adds v to the "danmaku_count" field.
func (u *HotspotUpsertOne) AddDanmakuCount(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddDanmakuCount(v)
	})
}

// UpdateDanmakuCount sets the "danmaku_count" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateDanmakuCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateDanmakuCount()
	})
}

// ClearDanmakuCount clears the value of the "danmaku_count" field.
func (u *HotspotUpsertOne) ClearDanmakuCount() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearDanmakuCount()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *HotspotUpsertOne) SetAuthorName(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateAuthorName() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorName()
	})
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *HotspotUpsertOne) ClearAuthorName() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorName()
	})
}

// SetAuthorUsername sets the "author_username" field.
func (u *HotspotUpsertOne) SetAuthorUsername(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorUsername(v)
	})
}

// UpdateAuthorUsername sets the "author_username" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateAuthorUsername() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorUsername()
	})
}

// ClearAuthorUsername clears the value of the "author_username" field.
func (u *HotspotUpsertOne) ClearAuthorUsername() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorUsername()
	})
}

// SetAuthorAvatar sets the "author_avatar" field.
func (u *HotspotUpsertOne) SetAuthorAvatar(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorAvatar(v)
	})
}

// UpdateAuthorAvatar sets the "author_avatar" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateAuthorAvatar() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorAvatar()
	})
}

// ClearAuthorAvatar clears the value of the "author_avatar" field.
func (u *HotspotUpsertOne) ClearAuthorAvatar() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorAvatar()
	})
}

// SetAuthorFollowers sets the "author_followers" field.
func (u *HotspotUpsertOne) SetAuthorFollowers(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorFollowers(v)
	})
}

// AddAuthorFollowers adds v to the "author_followers" field.
func (u *HotspotUpsertOne) AddAuthorFollowers(v int) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.AddAuthorFollowers(v)
	})
}

// UpdateAuthorFollowers sets the "author_followers" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateAuthorFollowers() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorFollowers()
	})
}

// ClearAuthorFollowers clears the value of the "author_followers" field.
func (u *HotspotUpsertOne) ClearAuthorFollowers() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorFollowers()
	})
}

// SetAuthorVerified sets the "author_verified" field.
func (u *HotspotUpsertOne) SetAuthorVerified(v bool) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorVerified(v)
	})
}

// UpdateAuthorVerified sets the "author_verified" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateAuthorVerified() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorVerified()
	})
}

// ClearAuthorVerified clears the value of the "author_verified" field.
func (u *HotspotUpsertOne) ClearAuthorVerified() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorVerified()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *HotspotUpsertOne) SetPublishedAt(v time.Time) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdatePublishedAt() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *HotspotUpsertOne) ClearPublishedAt() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearPublishedAt()
	})
}

// SetKeywordID sets the "keyword_id" field.
func (u *HotspotUpsertOne) SetKeywordID(v string) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetKeywordID(v)
	})
}

// UpdateKeywordID sets the "keyword_id" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateKeywordID() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateKeywordID()
	})
}

// ClearKeywordID clears the value of the "keyword_id" field.
func (u *HotspotUpsertOne) ClearKeywordID() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearKeywordID()
	})
}

// SetIsNotified sets the "is_notified" field.
func (u *HotspotUpsertOne) SetIsNotified(v bool) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetIsNotified(v)
	})
}

// UpdateIsNotified sets the "is_notified" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateIsNotified() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateIsNotified()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *HotspotUpsertOne) SetNotifiedAt(v time.Time) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateNotifiedAt() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateNotifiedAt()
	})
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *HotspotUpsertOne) ClearNotifiedAt() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearNotifiedAt()
	})
}

// SetIsRead sets the "is_read" field.
func (u *HotspotUpsertOne) SetIsRead(v bool) *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.SetIsRead(v)
	})
}

// UpdateIsRead sets the "is_read" field to the value that was provided on create.
func (u *HotspotUpsertOne) UpdateIsRead() *HotspotUpsertOne {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateIsRead()
	})
}

// Exec executes the query.
func (u *HotspotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HotspotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HotspotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HotspotUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: HotspotUpsertOne.ID is not supported by MySQL driver. Use HotspotUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HotspotUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HotspotCreateBulk is the builder for creating many Hotspot entities in bulk.
type HotspotCreateBulk struct {
	config
	err      error
	builders []*HotspotCreate
	conflict []sql.ConflictOption
}

// Save creates the Hotspot entities in the database.
func (_c *HotspotCreateBulk) Save(ctx context.Context) ([]*Hotspot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Hotspot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HotspotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HotspotCreateBulk) SaveX(ctx context.Context) []*Hotspot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HotspotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HotspotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Hotspot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HotspotUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *HotspotCreateBulk) OnConflict(opts ...sql.ConflictOption) *HotspotUpsertBulk {
	_c.conflict = opts
	return &HotspotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Hotspot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HotspotCreateBulk) OnConflictColumns(columns ...string) *HotspotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HotspotUpsertBulk{
		create: _c,
	}
}

// HotspotUpsertBulk is the builder for "upsert"-ing
// a bulk of Hotspot nodes.
type HotspotUpsertBulk struct {
	create *HotspotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Hotspot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(hotspot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HotspotUpsertBulk) UpdateNewValues() *HotspotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(hotspot.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(hotspot.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Hotspot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HotspotUpsertBulk) Ignore() *HotspotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HotspotUpsertBulk) DoNothing() *HotspotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HotspotCreateBulk.OnConflict
// documentation for more info.
func (u *HotspotUpsertBulk) Update(set func(*HotspotUpsert)) *HotspotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HotspotUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *HotspotUpsertBulk) SetTitle(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateTitle() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *HotspotUpsertBulk) SetContent(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateContent() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateContent()
	})
}

// SetURL sets the "url" field.
func (u *HotspotUpsertBulk) SetURL(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateURL() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateURL()
	})
}

// SetSource sets the "source" field.
func (u *HotspotUpsertBulk) SetSource(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateSource() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateSource()
	})
}

// SetSourceID sets the "source_id" field.
func (u *HotspotUpsertBulk) SetSourceID(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateSourceID() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateSourceID()
	})
}

// ClearSourceID clears the value of the "source_id" field.
func (u *HotspotUpsertBulk) ClearSourceID() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearSourceID()
	})
}

// SetIsReal sets the "is_real" field.
func (u *HotspotUpsertBulk) SetIsReal(v bool) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetIsReal(v)
	})
}

// UpdateIsReal sets the "is_real" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateIsReal() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateIsReal()
	})
}

// SetRelevance sets the "relevance" field.
func (u *HotspotUpsertBulk) SetRelevance(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetRelevance(v)
	})
}

// AddRelevance adds v to the "relevance" field.
func (u *HotspotUpsertBulk) AddRelevance(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddRelevance(v)
	})
}

// UpdateRelevance sets the "relevance" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateRelevance() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateRelevance()
	})
}

// SetRelevanceReason sets the "relevance_reason" field.
func (u *HotspotUpsertBulk) SetRelevanceReason(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetRelevanceReason(v)
	})
}

// UpdateRelevanceReason sets the "relevance_reason" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateRelevanceReason() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateRelevanceReason()
	})
}

// ClearRelevanceReason clears the value of the "relevance_reason" field.
func (u *HotspotUpsertBulk) ClearRelevanceReason() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearRelevanceReason()
	})
}

// SetKeywordMentioned sets the "keyword_mentioned" field.
func (u *HotspotUpsertBulk) SetKeywordMentioned(v bool) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetKeywordMentioned(v)
	})
}

// UpdateKeywordMentioned sets the "keyword_mentioned" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateKeywordMentioned() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateKeywordMentioned()
	})
}

// ClearKeywordMentioned clears the value of the "keyword_mentioned" field.
func (u *HotspotUpsertBulk) ClearKeywordMentioned() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearKeywordMentioned()
	})
}

// SetImportance sets the "importance" field.
func (u *HotspotUpsertBulk) SetImportance(v types.Importance) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetImportance(v)
	})
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateImportance() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateImportance()
	})
}

// SetSummary sets the "summary" field.
func (u *HotspotUpsertBulk) SetSummary(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateSummary() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *HotspotUpsertBulk) ClearSummary() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearSummary()
	})
}

// SetViewCount sets the "view_count" field.
func (u *HotspotUpsertBulk) SetViewCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *HotspotUpsertBulk) AddViewCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateViewCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateViewCount()
	})
}

// ClearViewCount clears the value of the "view_count" field.
func (u *HotspotUpsertBulk) ClearViewCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearViewCount()
	})
}

// SetLikeCount sets the "like_count" field.
func (u *HotspotUpsertBulk) SetLikeCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetLikeCount(v)
	})
}

// AddLikeCount adds v to the "like_count" field.
func (u *HotspotUpsertBulk) AddLikeCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddLikeCount(v)
	})
}

// UpdateLikeCount sets the "like_count" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateLikeCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateLikeCount()
	})
}

// ClearLikeCount clears the value of the "like_count" field.
func (u *HotspotUpsertBulk) ClearLikeCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearLikeCount()
	})
}

// SetRetweetCount sets the "retweet_count" field.
func (u *HotspotUpsertBulk) SetRetweetCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetRetweetCount(v)
	})
}

// AddRetweetCount adds v to the "retweet_count" field.
func (u *HotspotUpsertBulk) AddRetweetCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddRetweetCount(v)
	})
}

// UpdateRetweetCount sets the "retweet_count" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateRetweetCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateRetweetCount()
	})
}

// ClearRetweetCount clears the value of the "retweet_count" field.
func (u *HotspotUpsertBulk) ClearRetweetCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearRetweetCount()
	})
}

// SetReplyCount sets the "reply_count" field.
func (u *HotspotUpsertBulk) SetReplyCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetReplyCount(v)
	})
}

// AddReplyCount adds v to the "reply_count" field.
func (u *HotspotUpsertBulk) AddReplyCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddReplyCount(v)
	})
}

// UpdateReplyCount sets the "reply_count" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateReplyCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateReplyCount()
	})
}

// ClearReplyCount clears the value of the "reply_count" field.
func (u *HotspotUpsertBulk) ClearReplyCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearReplyCount()
	})
}

// SetCommentCount sets the "comment_count" field.
func (u *HotspotUpsertBulk) SetCommentCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetCommentCount(v)
	})
}

// AddCommentCount adds v to the "comment_count" field.
func (u *HotspotUpsertBulk) AddCommentCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddCommentCount(v)
	})
}

// UpdateCommentCount sets the "comment_count" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateCommentCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateCommentCount()
	})
}

// ClearCommentCount clears the value of the "comment_count" field.
func (u *HotspotUpsertBulk) ClearCommentCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearCommentCount()
	})
}

// SetQuoteCount sets the "quote_count" field.
func (u *HotspotUpsertBulk) SetQuoteCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetQuoteCount(v)
	})
}

// AddQuoteCount adds v to the "quote_count" field.
func (u *HotspotUpsertBulk) AddQuoteCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddQuoteCount(v)
	})
}

// UpdateQuoteCount sets the "quote_count" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateQuoteCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateQuoteCount()
	})
}

// ClearQuoteCount clears the value of the "quote_count" field.
func (u *HotspotUpsertBulk) ClearQuoteCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearQuoteCount()
	})
}

// SetDanmakuCount sets the "danmaku_count" field.
func (u *HotspotUpsertBulk) SetDanmakuCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetDanmakuCount(v)
	})
}

// AddDanmakuCount adds v to the "danmaku_count" field.
func (u *HotspotUpsertBulk) AddDanmakuCount(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddDanmakuCount(v)
	})
}

// UpdateDanmakuCount sets the "danmaku_count" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateDanmakuCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateDanmakuCount()
	})
}

// ClearDanmakuCount clears the value of the "danmaku_count" field.
func (u *HotspotUpsertBulk) ClearDanmakuCount() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearDanmakuCount()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *HotspotUpsertBulk) SetAuthorName(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateAuthorName() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorName()
	})
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *HotspotUpsertBulk) ClearAuthorName() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorName()
	})
}

// SetAuthorUsername sets the "author_username" field.
func (u *HotspotUpsertBulk) SetAuthorUsername(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorUsername(v)
	})
}

// UpdateAuthorUsername sets the "author_username" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateAuthorUsername() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorUsername()
	})
}

// ClearAuthorUsername clears the value of the "author_username" field.
func (u *HotspotUpsertBulk) ClearAuthorUsername() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorUsername()
	})
}

// SetAuthorAvatar sets the "author_avatar" field.
func (u *HotspotUpsertBulk) SetAuthorAvatar(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorAvatar(v)
	})
}

// UpdateAuthorAvatar sets the "author_avatar" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateAuthorAvatar() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorAvatar()
	})
}

// ClearAuthorAvatar clears the value of the "author_avatar" field.
func (u *HotspotUpsertBulk) ClearAuthorAvatar() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorAvatar()
	})
}

// SetAuthorFollowers sets the "author_followers" field.
func (u *HotspotUpsertBulk) SetAuthorFollowers(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorFollowers(v)
	})
}

// AddAuthorFollowers adds v to the "author_followers" field.
func (u *HotspotUpsertBulk) AddAuthorFollowers(v int) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.AddAuthorFollowers(v)
	})
}

// UpdateAuthorFollowers sets the "author_followers" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateAuthorFollowers() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorFollowers()
	})
}

// ClearAuthorFollowers clears the value of the "author_followers" field.
func (u *HotspotUpsertBulk) ClearAuthorFollowers() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorFollowers()
	})
}

// SetAuthorVerified sets the "author_verified" field.
func (u *HotspotUpsertBulk) SetAuthorVerified(v bool) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetAuthorVerified(v)
	})
}

// UpdateAuthorVerified sets the "author_verified" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateAuthorVerified() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateAuthorVerified()
	})
}

// ClearAuthorVerified clears the value of the "author_verified" field.
func (u *HotspotUpsertBulk) ClearAuthorVerified() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearAuthorVerified()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *HotspotUpsertBulk) SetPublishedAt(v time.Time) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdatePublishedAt() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *HotspotUpsertBulk) ClearPublishedAt() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearPublishedAt()
	})
}

// SetKeywordID sets the "keyword_id" field.
func (u *HotspotUpsertBulk) SetKeywordID(v string) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetKeywordID(v)
	})
}

// UpdateKeywordID sets the "keyword_id" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateKeywordID() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateKeywordID()
	})
}

// ClearKeywordID clears the value of the "keyword_id" field.
func (u *HotspotUpsertBulk) ClearKeywordID() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearKeywordID()
	})
}

// SetIsNotified sets the "is_notified" field.
func (u *HotspotUpsertBulk) SetIsNotified(v bool) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetIsNotified(v)
	})
}

// UpdateIsNotified sets the "is_notified" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateIsNotified() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateIsNotified()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *HotspotUpsertBulk) SetNotifiedAt(v time.Time) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateNotifiedAt() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateNotifiedAt()
	})
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *HotspotUpsertBulk) ClearNotifiedAt() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.ClearNotifiedAt()
	})
}

// SetIsRead sets the "is_read" field.
func (u *HotspotUpsertBulk) SetIsRead(v bool) *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.SetIsRead(v)
	})
}

// UpdateIsRead sets the "is_read" field to the value that was provided on create.
func (u *HotspotUpsertBulk) UpdateIsRead() *HotspotUpsertBulk {
	return u.Update(func(s *HotspotUpsert) {
		s.UpdateIsRead()
	})
}

// Exec executes the query.
func (u *HotspotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HotspotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HotspotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HotspotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
