// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	enthotspot "wood-hot-monitor/ent/hotspot"
	"wood-hot-monitor/ent/keyword"
	"wood-hot-monitor/ent/predicate"
	"wood-hot-monitor/internal/hotspot"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HotspotUpdate is the builder for updating Hotspot entities.
type HotspotUpdate struct {
	config
	hooks    []Hook
	mutation *HotspotMutation
}

// Where appends a list predicates to the HotspotUpdate builder.
func (_u *HotspotUpdate) Where(ps ...predicate.Hotspot) *HotspotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *HotspotUpdate) SetTitle(v string) *HotspotUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableTitle(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *HotspotUpdate) SetContent(v string) *HotspotUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableContent(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *HotspotUpdate) SetURL(v string) *HotspotUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableURL(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *HotspotUpdate) SetSource(v string) *HotspotUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableSource(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *HotspotUpdate) SetSourceID(v string) *HotspotUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableSourceID(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *HotspotUpdate) ClearSourceID() *HotspotUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetIsReal sets the "is_real" field.
func (_u *HotspotUpdate) SetIsReal(v bool) *HotspotUpdate {
	_u.mutation.SetIsReal(v)
	return _u
}

// SetNillableIsReal sets the "is_real" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableIsReal(v *bool) *HotspotUpdate {
	if v != nil {
		_u.SetIsReal(*v)
	}
	return _u
}

// SetRelevance sets the "relevance" field.
func (_u *HotspotUpdate) SetRelevance(v int) *HotspotUpdate {
	_u.mutation.ResetRelevance()
	_u.mutation.SetRelevance(v)
	return _u
}

// SetNillableRelevance sets the "relevance" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableRelevance(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetRelevance(*v)
	}
	return _u
}

// AddRelevance adds value to the "relevance" field.
func (_u *HotspotUpdate) AddRelevance(v int) *HotspotUpdate {
	_u.mutation.AddRelevance(v)
	return _u
}

// SetRelevanceReason sets the "relevance_reason" field.
func (_u *HotspotUpdate) SetRelevanceReason(v string) *HotspotUpdate {
	_u.mutation.SetRelevanceReason(v)
	return _u
}

// SetNillableRelevanceReason sets the "relevance_reason" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableRelevanceReason(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetRelevanceReason(*v)
	}
	return _u
}

// ClearRelevanceReason clears the value of the "relevance_reason" field.
func (_u *HotspotUpdate) ClearRelevanceReason() *HotspotUpdate {
	_u.mutation.ClearRelevanceReason()
	return _u
}

// SetKeywordMentioned sets the "keyword_mentioned" field.
func (_u *HotspotUpdate) SetKeywordMentioned(v bool) *HotspotUpdate {
	_u.mutation.SetKeywordMentioned(v)
	return _u
}

// SetNillableKeywordMentioned sets the "keyword_mentioned" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableKeywordMentioned(v *bool) *HotspotUpdate {
	if v != nil {
		_u.SetKeywordMentioned(*v)
	}
	return _u
}

// ClearKeywordMentioned clears the value of the "keyword_mentioned" field.
func (_u *HotspotUpdate) ClearKeywordMentioned() *HotspotUpdate {
	_u.mutation.ClearKeywordMentioned()
	return _u
}

// SetImportance sets the "importance" field.
func (_u *HotspotUpdate) SetImportance(v hotspot.Importance) *HotspotUpdate {
	_u.mutation.SetImportance(v)
	return _u
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableImportance(v *hotspot.Importance) *HotspotUpdate {
	if v != nil {
		_u.SetImportance(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *HotspotUpdate) SetSummary(v string) *HotspotUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableSummary(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *HotspotUpdate) ClearSummary() *HotspotUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *HotspotUpdate) SetViewCount(v int) *HotspotUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableViewCount(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *HotspotUpdate) AddViewCount(v int) *HotspotUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// ClearViewCount clears the value of the "view_count" field.
func (_u *HotspotUpdate) ClearViewCount() *HotspotUpdate {
	_u.mutation.ClearViewCount()
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *HotspotUpdate) SetLikeCount(v int) *HotspotUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableLikeCount(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *HotspotUpdate) AddLikeCount(v int) *HotspotUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// ClearLikeCount clears the value of the "like_count" field.
func (_u *HotspotUpdate) ClearLikeCount() *HotspotUpdate {
	_u.mutation.ClearLikeCount()
	return _u
}

// SetRetweetCount sets the "retweet_count" field.
func (_u *HotspotUpdate) SetRetweetCount(v int) *HotspotUpdate {
	_u.mutation.ResetRetweetCount()
	_u.mutation.SetRetweetCount(v)
	return _u
}

// SetNillableRetweetCount sets the "retweet_count" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableRetweetCount(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetRetweetCount(*v)
	}
	return _u
}

// AddRetweetCount adds value to the "retweet_count" field.
func (_u *HotspotUpdate) AddRetweetCount(v int) *HotspotUpdate {
	_u.mutation.AddRetweetCount(v)
	return _u
}

// ClearRetweetCount clears the value of the "retweet_count" field.
func (_u *HotspotUpdate) ClearRetweetCount() *HotspotUpdate {
	_u.mutation.ClearRetweetCount()
	return _u
}

// SetReplyCount sets the "reply_count" field.
func (_u *HotspotUpdate) SetReplyCount(v int) *HotspotUpdate {
	_u.mutation.ResetReplyCount()
	_u.mutation.SetReplyCount(v)
	return _u
}

// SetNillableReplyCount sets the "reply_count" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableReplyCount(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetReplyCount(*v)
	}
	return _u
}

// AddReplyCount adds value to the "reply_count" field.
func (_u *HotspotUpdate) AddReplyCount(v int) *HotspotUpdate {
	_u.mutation.AddReplyCount(v)
	return _u
}

// ClearReplyCount clears the value of the "reply_count" field.
func (_u *HotspotUpdate) ClearReplyCount() *HotspotUpdate {
	_u.mutation.ClearReplyCount()
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *HotspotUpdate) SetCommentCount(v int) *HotspotUpdate {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableCommentCount(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *HotspotUpdate) AddCommentCount(v int) *HotspotUpdate {
	_u.mutation.AddCommentCount(v)
	return _u
}

// ClearCommentCount clears the value of the "comment_count" field.
func (_u *HotspotUpdate) ClearCommentCount() *HotspotUpdate {
	_u.mutation.ClearCommentCount()
	return _u
}

// SetQuoteCount sets the "quote_count" field.
func (_u *HotspotUpdate) SetQuoteCount(v int) *HotspotUpdate {
	_u.mutation.ResetQuoteCount()
	_u.mutation.SetQuoteCount(v)
	return _u
}

// SetNillableQuoteCount sets the "quote_count" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableQuoteCount(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetQuoteCount(*v)
	}
	return _u
}

// AddQuoteCount adds value to the "quote_count" field.
func (_u *HotspotUpdate) AddQuoteCount(v int) *HotspotUpdate {
	_u.mutation.AddQuoteCount(v)
	return _u
}

// ClearQuoteCount clears the value of the "quote_count" field.
func (_u *HotspotUpdate) ClearQuoteCount() *HotspotUpdate {
	_u.mutation.ClearQuoteCount()
	return _u
}

// SetDanmakuCount sets the "danmaku_count" field.
func (_u *HotspotUpdate) SetDanmakuCount(v int) *HotspotUpdate {
	_u.mutation.ResetDanmakuCount()
	_u.mutation.SetDanmakuCount(v)
	return _u
}

// SetNillableDanmakuCount sets the "danmaku_count" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableDanmakuCount(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetDanmakuCount(*v)
	}
	return _u
}

// AddDanmakuCount adds value to the "danmaku_count" field.
func (_u *HotspotUpdate) AddDanmakuCount(v int) *HotspotUpdate {
	_u.mutation.AddDanmakuCount(v)
	return _u
}

// ClearDanmakuCount clears the value of the "danmaku_count" field.
func (_u *HotspotUpdate) ClearDanmakuCount() *HotspotUpdate {
	_u.mutation.ClearDanmakuCount()
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *HotspotUpdate) SetAuthorName(v string) *HotspotUpdate {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableAuthorName(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// ClearAuthorName clears the value of the "author_name" field.
func (_u *HotspotUpdate) ClearAuthorName() *HotspotUpdate {
	_u.mutation.ClearAuthorName()
	return _u
}

// SetAuthorUsername sets the "author_username" field.
func (_u *HotspotUpdate) SetAuthorUsername(v string) *HotspotUpdate {
	_u.mutation.SetAuthorUsername(v)
	return _u
}

// SetNillableAuthorUsername sets the "author_username" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableAuthorUsername(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetAuthorUsername(*v)
	}
	return _u
}

// ClearAuthorUsername clears the value of the "author_username" field.
func (_u *HotspotUpdate) ClearAuthorUsername() *HotspotUpdate {
	_u.mutation.ClearAuthorUsername()
	return _u
}

// SetAuthorAvatar sets the "author_avatar" field.
func (_u *HotspotUpdate) SetAuthorAvatar(v string) *HotspotUpdate {
	_u.mutation.SetAuthorAvatar(v)
	return _u
}

// SetNillableAuthorAvatar sets the "author_avatar" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableAuthorAvatar(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetAuthorAvatar(*v)
	}
	return _u
}

// ClearAuthorAvatar clears the value of the "author_avatar" field.
func (_u *HotspotUpdate) ClearAuthorAvatar() *HotspotUpdate {
	_u.mutation.ClearAuthorAvatar()
	return _u
}

// SetAuthorFollowers sets the "author_followers" field.
func (_u *HotspotUpdate) SetAuthorFollowers(v int) *HotspotUpdate {
	_u.mutation.ResetAuthorFollowers()
	_u.mutation.SetAuthorFollowers(v)
	return _u
}

// SetNillableAuthorFollowers sets the "author_followers" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableAuthorFollowers(v *int) *HotspotUpdate {
	if v != nil {
		_u.SetAuthorFollowers(*v)
	}
	return _u
}

// AddAuthorFollowers adds value to the "author_followers" field.
func (_u *HotspotUpdate) AddAuthorFollowers(v int) *HotspotUpdate {
	_u.mutation.AddAuthorFollowers(v)
	return _u
}

// ClearAuthorFollowers clears the value of the "author_followers" field.
func (_u *HotspotUpdate) ClearAuthorFollowers() *HotspotUpdate {
	_u.mutation.ClearAuthorFollowers()
	return _u
}

// SetAuthorVerified sets the "author_verified" field.
func (_u *HotspotUpdate) SetAuthorVerified(v bool) *HotspotUpdate {
	_u.mutation.SetAuthorVerified(v)
	return _u
}

// SetNillableAuthorVerified sets the "author_verified" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableAuthorVerified(v *bool) *HotspotUpdate {
	if v != nil {
		_u.SetAuthorVerified(*v)
	}
	return _u
}

// ClearAuthorVerified clears the value of the "author_verified" field.
func (_u *HotspotUpdate) ClearAuthorVerified() *HotspotUpdate {
	_u.mutation.ClearAuthorVerified()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *HotspotUpdate) SetPublishedAt(v time.Time) *HotspotUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillablePublishedAt(v *time.Time) *HotspotUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *HotspotUpdate) ClearPublishedAt() *HotspotUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetKeywordID sets the "keyword_id" field.
func (_u *HotspotUpdate) SetKeywordID(v string) *HotspotUpdate {
	_u.mutation.SetKeywordID(v)
	return _u
}

// SetNillableKeywordID sets the "keyword_id" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableKeywordID(v *string) *HotspotUpdate {
	if v != nil {
		_u.SetKeywordID(*v)
	}
	return _u
}

// ClearKeywordID clears the value of the "keyword_id" field.
func (_u *HotspotUpdate) ClearKeywordID() *HotspotUpdate {
	_u.mutation.ClearKeywordID()
	return _u
}

// SetIsNotified sets the "is_notified" field.
func (_u *HotspotUpdate) SetIsNotified(v bool) *HotspotUpdate {
	_u.mutation.SetIsNotified(v)
	return _u
}

// SetNillableIsNotified sets the "is_notified" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableIsNotified(v *bool) *HotspotUpdate {
	if v != nil {
		_u.SetIsNotified(*v)
	}
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *HotspotUpdate) SetNotifiedAt(v time.Time) *HotspotUpdate {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableNotifiedAt(v *time.Time) *HotspotUpdate {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *HotspotUpdate) ClearNotifiedAt() *HotspotUpdate {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *HotspotUpdate) SetIsRead(v bool) *HotspotUpdate {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *HotspotUpdate) SetNillableIsRead(v *bool) *HotspotUpdate {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetKeyword sets the "keyword" edge to the Keyword entity.
func (_u *HotspotUpdate) SetKeyword(v *Keyword) *HotspotUpdate {
	return _u.SetKeywordID(v.ID)
}

// Mutation returns the HotspotMutation object of the builder.
func (_u *HotspotUpdate) Mutation() *HotspotMutation {
	return _u.mutation
}

// ClearKeyword clears the "keyword" edge to the Keyword entity.
func (_u *HotspotUpdate) ClearKeyword() *HotspotUpdate {
	_u.mutation.ClearKeyword()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HotspotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotspotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HotspotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotspotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HotspotUpdate) check() error {
	if v, ok := _u.mutation.Importance(); ok {
		if err := enthotspot.ImportanceValidator(v); err != nil {
			return &ValidationError{Name: "importance", err: fmt.Errorf(`ent: validator failed for field "Hotspot.importance": %w`, err)}
		}
	}
	return nil
}

func (_u *HotspotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enthotspot.Table, enthotspot.Columns, sqlgraph.NewFieldSpec(enthotspot.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(enthotspot.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(enthotspot.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(enthotspot.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(enthotspot.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(enthotspot.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(enthotspot.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.IsReal(); ok {
		_spec.SetField(enthotspot.FieldIsReal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Relevance(); ok {
		_spec.SetField(enthotspot.FieldRelevance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRelevance(); ok {
		_spec.AddField(enthotspot.FieldRelevance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RelevanceReason(); ok {
		_spec.SetField(enthotspot.FieldRelevanceReason, field.TypeString, value)
	}
	if _u.mutation.RelevanceReasonCleared() {
		_spec.ClearField(enthotspot.FieldRelevanceReason, field.TypeString)
	}
	if value, ok := _u.mutation.KeywordMentioned(); ok {
		_spec.SetField(enthotspot.FieldKeywordMentioned, field.TypeBool, value)
	}
	if _u.mutation.KeywordMentionedCleared() {
		_spec.ClearField(enthotspot.FieldKeywordMentioned, field.TypeBool)
	}
	if value, ok := _u.mutation.Importance(); ok {
		_spec.SetField(enthotspot.FieldImportance, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(enthotspot.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(enthotspot.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(enthotspot.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(enthotspot.FieldViewCount, field.TypeInt, value)
	}
	if _u.mutation.ViewCountCleared() {
		_spec.ClearField(enthotspot.FieldViewCount, field.TypeInt)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(enthotspot.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(enthotspot.FieldLikeCount, field.TypeInt, value)
	}
	if _u.mutation.LikeCountCleared() {
		_spec.ClearField(enthotspot.FieldLikeCount, field.TypeInt)
	}
	if value, ok := _u.mutation.RetweetCount(); ok {
		_spec.SetField(enthotspot.FieldRetweetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetweetCount(); ok {
		_spec.AddField(enthotspot.FieldRetweetCount, field.TypeInt, value)
	}
	if _u.mutation.RetweetCountCleared() {
		_spec.ClearField(enthotspot.FieldRetweetCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ReplyCount(); ok {
		_spec.SetField(enthotspot.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReplyCount(); ok {
		_spec.AddField(enthotspot.FieldReplyCount, field.TypeInt, value)
	}
	if _u.mutation.ReplyCountCleared() {
		_spec.ClearField(enthotspot.FieldReplyCount, field.TypeInt)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(enthotspot.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(enthotspot.FieldCommentCount, field.TypeInt, value)
	}
	if _u.mutation.CommentCountCleared() {
		_spec.ClearField(enthotspot.FieldCommentCount, field.TypeInt)
	}
	if value, ok := _u.mutation.QuoteCount(); ok {
		_spec.SetField(enthotspot.FieldQuoteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuoteCount(); ok {
		_spec.AddField(enthotspot.FieldQuoteCount, field.TypeInt, value)
	}
	if _u.mutation.QuoteCountCleared() {
		_spec.ClearField(enthotspot.FieldQuoteCount, field.TypeInt)
	}
	if value, ok := _u.mutation.DanmakuCount(); ok {
		_spec.SetField(enthotspot.FieldDanmakuCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDanmakuCount(); ok {
		_spec.AddField(enthotspot.FieldDanmakuCount, field.TypeInt, value)
	}
	if _u.mutation.DanmakuCountCleared() {
		_spec.ClearField(enthotspot.FieldDanmakuCount, field.TypeInt)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(enthotspot.FieldAuthorName, field.TypeString, value)
	}
	if _u.mutation.AuthorNameCleared() {
		_spec.ClearField(enthotspot.FieldAuthorName, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorUsername(); ok {
		_spec.SetField(enthotspot.FieldAuthorUsername, field.TypeString, value)
	}
	if _u.mutation.AuthorUsernameCleared() {
		_spec.ClearField(enthotspot.FieldAuthorUsername, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorAvatar(); ok {
		_spec.SetField(enthotspot.FieldAuthorAvatar, field.TypeString, value)
	}
	if _u.mutation.AuthorAvatarCleared() {
		_spec.ClearField(enthotspot.FieldAuthorAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorFollowers(); ok {
		_spec.SetField(enthotspot.FieldAuthorFollowers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAuthorFollowers(); ok {
		_spec.AddField(enthotspot.FieldAuthorFollowers, field.TypeInt, value)
	}
	if _u.mutation.AuthorFollowersCleared() {
		_spec.ClearField(enthotspot.FieldAuthorFollowers, field.TypeInt)
	}
	if value, ok := _u.mutation.AuthorVerified(); ok {
		_spec.SetField(enthotspot.FieldAuthorVerified, field.TypeBool, value)
	}
	if _u.mutation.AuthorVerifiedCleared() {
		_spec.ClearField(enthotspot.FieldAuthorVerified, field.TypeBool)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(enthotspot.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(enthotspot.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsNotified(); ok {
		_spec.SetField(enthotspot.FieldIsNotified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(enthotspot.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(enthotspot.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(enthotspot.FieldIsRead, field.TypeBool, value)
	}
	if _u.mutation.KeywordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enthotspot.KeywordTable,
			Columns: []string{enthotspot.KeywordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeywordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enthotspot.KeywordTable,
			Columns: []string{enthotspot.KeywordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enthotspot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HotspotUpdateOne is the builder for updating a single Hotspot entity.
type HotspotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HotspotMutation
}

// SetTitle sets the "title" field.
func (_u *HotspotUpdateOne) SetTitle(v string) *HotspotUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableTitle(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *HotspotUpdateOne) SetContent(v string) *HotspotUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableContent(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *HotspotUpdateOne) SetURL(v string) *HotspotUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableURL(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *HotspotUpdateOne) SetSource(v string) *HotspotUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableSource(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *HotspotUpdateOne) SetSourceID(v string) *HotspotUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableSourceID(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *HotspotUpdateOne) ClearSourceID() *HotspotUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetIsReal sets the "is_real" field.
func (_u *HotspotUpdateOne) SetIsReal(v bool) *HotspotUpdateOne {
	_u.mutation.SetIsReal(v)
	return _u
}

// SetNillableIsReal sets the "is_real" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableIsReal(v *bool) *HotspotUpdateOne {
	if v != nil {
		_u.SetIsReal(*v)
	}
	return _u
}

// SetRelevance sets the "relevance" field.
func (_u *HotspotUpdateOne) SetRelevance(v int) *HotspotUpdateOne {
	_u.mutation.ResetRelevance()
	_u.mutation.SetRelevance(v)
	return _u
}

// SetNillableRelevance sets the "relevance" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableRelevance(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetRelevance(*v)
	}
	return _u
}

// AddRelevance adds value to the "relevance" field.
func (_u *HotspotUpdateOne) AddRelevance(v int) *HotspotUpdateOne {
	_u.mutation.AddRelevance(v)
	return _u
}

// SetRelevanceReason sets the "relevance_reason" field.
func (_u *HotspotUpdateOne) SetRelevanceReason(v string) *HotspotUpdateOne {
	_u.mutation.SetRelevanceReason(v)
	return _u
}

// SetNillableRelevanceReason sets the "relevance_reason" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableRelevanceReason(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetRelevanceReason(*v)
	}
	return _u
}

// ClearRelevanceReason clears the value of the "relevance_reason" field.
func (_u *HotspotUpdateOne) ClearRelevanceReason() *HotspotUpdateOne {
	_u.mutation.ClearRelevanceReason()
	return _u
}

// SetKeywordMentioned sets the "keyword_mentioned" field.
func (_u *HotspotUpdateOne) SetKeywordMentioned(v bool) *HotspotUpdateOne {
	_u.mutation.SetKeywordMentioned(v)
	return _u
}

// SetNillableKeywordMentioned sets the "keyword_mentioned" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableKeywordMentioned(v *bool) *HotspotUpdateOne {
	if v != nil {
		_u.SetKeywordMentioned(*v)
	}
	return _u
}

// ClearKeywordMentioned clears the value of the "keyword_mentioned" field.
func (_u *HotspotUpdateOne) ClearKeywordMentioned() *HotspotUpdateOne {
	_u.mutation.ClearKeywordMentioned()
	return _u
}

// SetImportance sets the "importance" field.
func (_u *HotspotUpdateOne) SetImportance(v hotspot.Importance) *HotspotUpdateOne {
	_u.mutation.SetImportance(v)
	return _u
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableImportance(v *hotspot.Importance) *HotspotUpdateOne {
	if v != nil {
		_u.SetImportance(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *HotspotUpdateOne) SetSummary(v string) *HotspotUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableSummary(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *HotspotUpdateOne) ClearSummary() *HotspotUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *HotspotUpdateOne) SetViewCount(v int) *HotspotUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableViewCount(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *HotspotUpdateOne) AddViewCount(v int) *HotspotUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// ClearViewCount clears the value of the "view_count" field.
func (_u *HotspotUpdateOne) ClearViewCount() *HotspotUpdateOne {
	_u.mutation.ClearViewCount()
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *HotspotUpdateOne) SetLikeCount(v int) *HotspotUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableLikeCount(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *HotspotUpdateOne) AddLikeCount(v int) *HotspotUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// ClearLikeCount clears the value of the "like_count" field.
func (_u *HotspotUpdateOne) ClearLikeCount() *HotspotUpdateOne {
	_u.mutation.ClearLikeCount()
	return _u
}

// SetRetweetCount sets the "retweet_count" field.
func (_u *HotspotUpdateOne) SetRetweetCount(v int) *HotspotUpdateOne {
	_u.mutation.ResetRetweetCount()
	_u.mutation.SetRetweetCount(v)
	return _u
}

// SetNillableRetweetCount sets the "retweet_count" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableRetweetCount(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetRetweetCount(*v)
	}
	return _u
}

// AddRetweetCount adds value to the "retweet_count" field.
func (_u *HotspotUpdateOne) AddRetweetCount(v int) *HotspotUpdateOne {
	_u.mutation.AddRetweetCount(v)
	return _u
}

// ClearRetweetCount clears the value of the "retweet_count" field.
func (_u *HotspotUpdateOne) ClearRetweetCount() *HotspotUpdateOne {
	_u.mutation.ClearRetweetCount()
	return _u
}

// SetReplyCount sets the "reply_count" field.
func (_u *HotspotUpdateOne) SetReplyCount(v int) *HotspotUpdateOne {
	_u.mutation.ResetReplyCount()
	_u.mutation.SetReplyCount(v)
	return _u
}

// SetNillableReplyCount sets the "reply_count" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableReplyCount(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetReplyCount(*v)
	}
	return _u
}

// AddReplyCount adds value to the "reply_count" field.
func (_u *HotspotUpdateOne) AddReplyCount(v int) *HotspotUpdateOne {
	_u.mutation.AddReplyCount(v)
	return _u
}

// ClearReplyCount clears the value of the "reply_count" field.
func (_u *HotspotUpdateOne) ClearReplyCount() *HotspotUpdateOne {
	_u.mutation.ClearReplyCount()
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *HotspotUpdateOne) SetCommentCount(v int) *HotspotUpdateOne {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableCommentCount(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *HotspotUpdateOne) AddCommentCount(v int) *HotspotUpdateOne {
	_u.mutation.AddCommentCount(v)
	return _u
}

// ClearCommentCount clears the value of the "comment_count" field.
func (_u *HotspotUpdateOne) ClearCommentCount() *HotspotUpdateOne {
	_u.mutation.ClearCommentCount()
	return _u
}

// SetQuoteCount sets the "quote_count" field.
func (_u *HotspotUpdateOne) SetQuoteCount(v int) *HotspotUpdateOne {
	_u.mutation.ResetQuoteCount()
	_u.mutation.SetQuoteCount(v)
	return _u
}

// SetNillableQuoteCount sets the "quote_count" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableQuoteCount(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetQuoteCount(*v)
	}
	return _u
}

// AddQuoteCount adds value to the "quote_count" field.
func (_u *HotspotUpdateOne) AddQuoteCount(v int) *HotspotUpdateOne {
	_u.mutation.AddQuoteCount(v)
	return _u
}

// ClearQuoteCount clears the value of the "quote_count" field.
func (_u *HotspotUpdateOne) ClearQuoteCount() *HotspotUpdateOne {
	_u.mutation.ClearQuoteCount()
	return _u
}

// SetDanmakuCount sets the "danmaku_count" field.
func (_u *HotspotUpdateOne) SetDanmakuCount(v int) *HotspotUpdateOne {
	_u.mutation.ResetDanmakuCount()
	_u.mutation.SetDanmakuCount(v)
	return _u
}

// SetNillableDanmakuCount sets the "danmaku_count" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableDanmakuCount(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetDanmakuCount(*v)
	}
	return _u
}

// AddDanmakuCount adds value to the "danmaku_count" field.
func (_u *HotspotUpdateOne) AddDanmakuCount(v int) *HotspotUpdateOne {
	_u.mutation.AddDanmakuCount(v)
	return _u
}

// ClearDanmakuCount clears the value of the "danmaku_count" field.
func (_u *HotspotUpdateOne) ClearDanmakuCount() *HotspotUpdateOne {
	_u.mutation.ClearDanmakuCount()
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *HotspotUpdateOne) SetAuthorName(v string) *HotspotUpdateOne {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableAuthorName(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// ClearAuthorName clears the value of the "author_name" field.
func (_u *HotspotUpdateOne) ClearAuthorName() *HotspotUpdateOne {
	_u.mutation.ClearAuthorName()
	return _u
}

// SetAuthorUsername sets the "author_username" field.
func (_u *HotspotUpdateOne) SetAuthorUsername(v string) *HotspotUpdateOne {
	_u.mutation.SetAuthorUsername(v)
	return _u
}

// SetNillableAuthorUsername sets the "author_username" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableAuthorUsername(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetAuthorUsername(*v)
	}
	return _u
}

// ClearAuthorUsername clears the value of the "author_username" field.
func (_u *HotspotUpdateOne) ClearAuthorUsername() *HotspotUpdateOne {
	_u.mutation.ClearAuthorUsername()
	return _u
}

// SetAuthorAvatar sets the "author_avatar" field.
func (_u *HotspotUpdateOne) SetAuthorAvatar(v string) *HotspotUpdateOne {
	_u.mutation.SetAuthorAvatar(v)
	return _u
}

// SetNillableAuthorAvatar sets the "author_avatar" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableAuthorAvatar(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetAuthorAvatar(*v)
	}
	return _u
}

// ClearAuthorAvatar clears the value of the "author_avatar" field.
func (_u *HotspotUpdateOne) ClearAuthorAvatar() *HotspotUpdateOne {
	_u.mutation.ClearAuthorAvatar()
	return _u
}

// SetAuthorFollowers sets the "author_followers" field.
func (_u *HotspotUpdateOne) SetAuthorFollowers(v int) *HotspotUpdateOne {
	_u.mutation.ResetAuthorFollowers()
	_u.mutation.SetAuthorFollowers(v)
	return _u
}

// SetNillableAuthorFollowers sets the "author_followers" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableAuthorFollowers(v *int) *HotspotUpdateOne {
	if v != nil {
		_u.SetAuthorFollowers(*v)
	}
	return _u
}

// AddAuthorFollowers adds value to the "author_followers" field.
func (_u *HotspotUpdateOne) AddAuthorFollowers(v int) *HotspotUpdateOne {
	_u.mutation.AddAuthorFollowers(v)
	return _u
}

// ClearAuthorFollowers clears the value of the "author_followers" field.
func (_u *HotspotUpdateOne) ClearAuthorFollowers() *HotspotUpdateOne {
	_u.mutation.ClearAuthorFollowers()
	return _u
}

// SetAuthorVerified sets the "author_verified" field.
func (_u *HotspotUpdateOne) SetAuthorVerified(v bool) *HotspotUpdateOne {
	_u.mutation.SetAuthorVerified(v)
	return _u
}

// SetNillableAuthorVerified sets the "author_verified" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableAuthorVerified(v *bool) *HotspotUpdateOne {
	if v != nil {
		_u.SetAuthorVerified(*v)
	}
	return _u
}

// ClearAuthorVerified clears the value of the "author_verified" field.
func (_u *HotspotUpdateOne) ClearAuthorVerified() *HotspotUpdateOne {
	_u.mutation.ClearAuthorVerified()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *HotspotUpdateOne) SetPublishedAt(v time.Time) *HotspotUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillablePublishedAt(v *time.Time) *HotspotUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *HotspotUpdateOne) ClearPublishedAt() *HotspotUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetKeywordID sets the "keyword_id" field.
func (_u *HotspotUpdateOne) SetKeywordID(v string) *HotspotUpdateOne {
	_u.mutation.SetKeywordID(v)
	return _u
}

// SetNillableKeywordID sets the "keyword_id" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableKeywordID(v *string) *HotspotUpdateOne {
	if v != nil {
		_u.SetKeywordID(*v)
	}
	return _u
}

// ClearKeywordID clears the value of the "keyword_id" field.
func (_u *HotspotUpdateOne) ClearKeywordID() *HotspotUpdateOne {
	_u.mutation.ClearKeywordID()
	return _u
}

// SetIsNotified sets the "is_notified" field.
func (_u *HotspotUpdateOne) SetIsNotified(v bool) *HotspotUpdateOne {
	_u.mutation.SetIsNotified(v)
	return _u
}

// SetNillableIsNotified sets the "is_notified" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableIsNotified(v *bool) *HotspotUpdateOne {
	if v != nil {
		_u.SetIsNotified(*v)
	}
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *HotspotUpdateOne) SetNotifiedAt(v time.Time) *HotspotUpdateOne {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableNotifiedAt(v *time.Time) *HotspotUpdateOne {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *HotspotUpdateOne) ClearNotifiedAt() *HotspotUpdateOne {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *HotspotUpdateOne) SetIsRead(v bool) *HotspotUpdateOne {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *HotspotUpdateOne) SetNillableIsRead(v *bool) *HotspotUpdateOne {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetKeyword sets the "keyword" edge to the Keyword entity.
func (_u *HotspotUpdateOne) SetKeyword(v *Keyword) *HotspotUpdateOne {
	return _u.SetKeywordID(v.ID)
}

// Mutation returns the HotspotMutation object of the builder.
func (_u *HotspotUpdateOne) Mutation() *HotspotMutation {
	return _u.mutation
}

// ClearKeyword clears the "keyword" edge to the Keyword entity.
func (_u *HotspotUpdateOne) ClearKeyword() *HotspotUpdateOne {
	_u.mutation.ClearKeyword()
	return _u
}

// Where appends a list predicates to the HotspotUpdate builder.
func (_u *HotspotUpdateOne) Where(ps ...predicate.Hotspot) *HotspotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HotspotUpdateOne) Select(field string, fields ...string) *HotspotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Hotspot entity.
func (_u *HotspotUpdateOne) Save(ctx context.Context) (*Hotspot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotspotUpdateOne) SaveX(ctx context.Context) *Hotspot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HotspotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotspotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HotspotUpdateOne) check() error {
	if v, ok := _u.mutation.Importance(); ok {
		if err := enthotspot.ImportanceValidator(v); err != nil {
			return &ValidationError{Name: "importance", err: fmt.Errorf(`ent: validator failed for field "Hotspot.importance": %w`, err)}
		}
	}
	return nil
}

func (_u *HotspotUpdateOne) sqlSave(ctx context.Context) (_node *Hotspot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enthotspot.Table, enthotspot.Columns, sqlgraph.NewFieldSpec(enthotspot.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hotspot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enthotspot.FieldID)
		for _, f := range fields {
			if !enthotspot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enthotspot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(enthotspot.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(enthotspot.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(enthotspot.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(enthotspot.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(enthotspot.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(enthotspot.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.IsReal(); ok {
		_spec.SetField(enthotspot.FieldIsReal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Relevance(); ok {
		_spec.SetField(enthotspot.FieldRelevance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRelevance(); ok {
		_spec.AddField(enthotspot.FieldRelevance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RelevanceReason(); ok {
		_spec.SetField(enthotspot.FieldRelevanceReason, field.TypeString, value)
	}
	if _u.mutation.RelevanceReasonCleared() {
		_spec.ClearField(enthotspot.FieldRelevanceReason, field.TypeString)
	}
	if value, ok := _u.mutation.KeywordMentioned(); ok {
		_spec.SetField(enthotspot.FieldKeywordMentioned, field.TypeBool, value)
	}
	if _u.mutation.KeywordMentionedCleared() {
		_spec.ClearField(enthotspot.FieldKeywordMentioned, field.TypeBool)
	}
	if value, ok := _u.mutation.Importance(); ok {
		_spec.SetField(enthotspot.FieldImportance, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(enthotspot.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(enthotspot.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(enthotspot.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(enthotspot.FieldViewCount, field.TypeInt, value)
	}
	if _u.mutation.ViewCountCleared() {
		_spec.ClearField(enthotspot.FieldViewCount, field.TypeInt)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(enthotspot.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(enthotspot.FieldLikeCount, field.TypeInt, value)
	}
	if _u.mutation.LikeCountCleared() {
		_spec.ClearField(enthotspot.FieldLikeCount, field.TypeInt)
	}
	if value, ok := _u.mutation.RetweetCount(); ok {
		_spec.SetField(enthotspot.FieldRetweetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetweetCount(); ok {
		_spec.AddField(enthotspot.FieldRetweetCount, field.TypeInt, value)
	}
	if _u.mutation.RetweetCountCleared() {
		_spec.ClearField(enthotspot.FieldRetweetCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ReplyCount(); ok {
		_spec.SetField(enthotspot.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReplyCount(); ok {
		_spec.AddField(enthotspot.FieldReplyCount, field.TypeInt, value)
	}
	if _u.mutation.ReplyCountCleared() {
		_spec.ClearField(enthotspot.FieldReplyCount, field.TypeInt)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(enthotspot.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(enthotspot.FieldCommentCount, field.TypeInt, value)
	}
	if _u.mutation.CommentCountCleared() {
		_spec.ClearField(enthotspot.FieldCommentCount, field.TypeInt)
	}
	if value, ok := _u.mutation.QuoteCount(); ok {
		_spec.SetField(enthotspot.FieldQuoteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuoteCount(); ok {
		_spec.AddField(enthotspot.FieldQuoteCount, field.TypeInt, value)
	}
	if _u.mutation.QuoteCountCleared() {
		_spec.ClearField(enthotspot.FieldQuoteCount, field.TypeInt)
	}
	if value, ok := _u.mutation.DanmakuCount(); ok {
		_spec.SetField(enthotspot.FieldDanmakuCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDanmakuCount(); ok {
		_spec.AddField(enthotspot.FieldDanmakuCount, field.TypeInt, value)
	}
	if _u.mutation.DanmakuCountCleared() {
		_spec.ClearField(enthotspot.FieldDanmakuCount, field.TypeInt)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(enthotspot.FieldAuthorName, field.TypeString, value)
	}
	if _u.mutation.AuthorNameCleared() {
		_spec.ClearField(enthotspot.FieldAuthorName, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorUsername(); ok {
		_spec.SetField(enthotspot.FieldAuthorUsername, field.TypeString, value)
	}
	if _u.mutation.AuthorUsernameCleared() {
		_spec.ClearField(enthotspot.FieldAuthorUsername, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorAvatar(); ok {
		_spec.SetField(enthotspot.FieldAuthorAvatar, field.TypeString, value)
	}
	if _u.mutation.AuthorAvatarCleared() {
		_spec.ClearField(enthotspot.FieldAuthorAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorFollowers(); ok {
		_spec.SetField(enthotspot.FieldAuthorFollowers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAuthorFollowers(); ok {
		_spec.AddField(enthotspot.FieldAuthorFollowers, field.TypeInt, value)
	}
	if _u.mutation.AuthorFollowersCleared() {
		_spec.ClearField(enthotspot.FieldAuthorFollowers, field.TypeInt)
	}
	if value, ok := _u.mutation.AuthorVerified(); ok {
		_spec.SetField(enthotspot.FieldAuthorVerified, field.TypeBool, value)
	}
	if _u.mutation.AuthorVerifiedCleared() {
		_spec.ClearField(enthotspot.FieldAuthorVerified, field.TypeBool)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(enthotspot.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(enthotspot.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsNotified(); ok {
		_spec.SetField(enthotspot.FieldIsNotified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(enthotspot.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(enthotspot.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(enthotspot.FieldIsRead, field.TypeBool, value)
	}
	if _u.mutation.KeywordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enthotspot.KeywordTable,
			Columns: []string{enthotspot.KeywordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeywordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enthotspot.KeywordTable,
			Columns: []string{enthotspot.KeywordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Hotspot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enthotspot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
