// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	enthotspot "wood-hot-monitor/ent/hotspot"
	"wood-hot-monitor/ent/keyword"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KeywordCreate is the builder for creating a Keyword entity.
type KeywordCreate struct {
	config
	mutation *KeywordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetText sets the "text" field.
func (_c *KeywordCreate) SetText(v string) *KeywordCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *KeywordCreate) SetCategory(v string) *KeywordCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *KeywordCreate) SetNillableCategory(v *string) *KeywordCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *KeywordCreate) SetIsActive(v bool) *KeywordCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *KeywordCreate) SetNillableIsActive(v *bool) *KeywordCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *KeywordCreate) SetCreatedAt(v time.Time) *KeywordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *KeywordCreate) SetUpdatedAt(v time.Time) *KeywordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *KeywordCreate) SetID(v string) *KeywordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KeywordCreate) SetNillableID(v *string) *KeywordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddHotspotIDs adds the "hotspots" edge to the Hotspot entity by IDs.
func (_c *KeywordCreate) AddHotspotIDs(ids ...string) *KeywordCreate {
	_c.mutation.AddHotspotIDs(ids...)
	return _c
}

// AddHotspots adds the "hotspots" edges to the Hotspot entity.
func (_c *KeywordCreate) AddHotspots(v ...*Hotspot) *KeywordCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddHotspotIDs(ids...)
}

// Mutation returns the KeywordMutation object of the builder.
func (_c *KeywordCreate) Mutation() *KeywordMutation {
	return _c.mutation
}

// Save creates the Keyword in the database.
func (_c *KeywordCreate) Save(ctx context.Context) (*Keyword, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KeywordCreate) SaveX(ctx context.Context) *Keyword {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeywordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeywordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KeywordCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := keyword.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := keyword.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KeywordCreate) check() error {
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Keyword.text"`)}
	}
	if v, ok := _c.mutation.Text(); ok {
		if err := keyword.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Keyword.text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Keyword.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Keyword.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Keyword.updated_at"`)}
	}
	return nil
}

func (_c *KeywordCreate) sqlSave(ctx context.Context) (*Keyword, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Keyword.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KeywordCreate) createSpec() (*Keyword, *sqlgraph.CreateSpec) {
	var (
		_node = &Keyword{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(keyword.Table, sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(keyword.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(keyword.FieldCategory, field.TypeString, value)
		_node.Category = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(keyword.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(keyword.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(keyword.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.HotspotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyword.HotspotsTable,
			Columns: []string{keyword.HotspotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enthotspot.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Keyword.Create().
//		SetText(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeywordUpsert) {
//			SetText(v+v).
//		}).
//		Exec(ctx)
func (_c *KeywordCreate) OnConflict(opts ...sql.ConflictOption) *KeywordUpsertOne {
	_c.conflict = opts
	return &KeywordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Keyword.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeywordCreate) OnConflictColumns(columns ...string) *KeywordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeywordUpsertOne{
		create: _c,
	}
}

type (
	// KeywordUpsertOne is the builder for "upsert"-ing
	//  one Keyword node.
	KeywordUpsertOne struct {
		create *KeywordCreate
	}

	// KeywordUpsert is the "OnConflict" setter.
	KeywordUpsert struct {
		*sql.UpdateSet
	}
)

// SetText sets the "text" field.
func (u *KeywordUpsert) SetText(v string) *KeywordUpsert {
	u.Set(keyword.FieldText, v)
	return u
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *KeywordUpsert) UpdateText() *KeywordUpsert {
	u.SetExcluded(keyword.FieldText)
	return u
}

// SetCategory sets the "category" field.
func (u *KeywordUpsert) SetCategory(v string) *KeywordUpsert {
	u.Set(keyword.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *KeywordUpsert) UpdateCategory() *KeywordUpsert {
	u.SetExcluded(keyword.FieldCategory)
	return u
}

// ClearCategory clears the value of the "category" field.
func (u *KeywordUpsert) ClearCategory() *KeywordUpsert {
	u.SetNull(keyword.FieldCategory)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *KeywordUpsert) SetIsActive(v bool) *KeywordUpsert {
	u.Set(keyword.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *KeywordUpsert) UpdateIsActive() *KeywordUpsert {
	u.SetExcluded(keyword.FieldIsActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KeywordUpsert) SetUpdatedAt(v time.Time) *KeywordUpsert {
	u.Set(keyword.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KeywordUpsert) UpdateUpdatedAt() *KeywordUpsert {
	u.SetExcluded(keyword.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Keyword.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(keyword.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeywordUpsertOne) UpdateNewValues() *KeywordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(keyword.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(keyword.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Keyword.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *KeywordUpsertOne) Ignore() *KeywordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeywordUpsertOne) DoNothing() *KeywordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeywordCreate.OnConflict
// documentation for more info.
func (u *KeywordUpsertOne) Update(set func(*KeywordUpsert)) *KeywordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeywordUpsert{UpdateSet: update})
	}))
	return u
}

// SetText sets the "text" field.
func (u *KeywordUpsertOne) SetText(v string) *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *KeywordUpsertOne) UpdateText() *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.UpdateText()
	})
}

// SetCategory sets the "category" field.
func (u *KeywordUpsertOne) SetCategory(v string) *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *KeywordUpsertOne) UpdateCategory() *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *KeywordUpsertOne) ClearCategory() *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.ClearCategory()
	})
}

// SetIsActive sets the "is_active" field.
func (u *KeywordUpsertOne) SetIsActive(v bool) *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *KeywordUpsertOne) UpdateIsActive() *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KeywordUpsertOne) SetUpdatedAt(v time.Time) *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KeywordUpsertOne) UpdateUpdatedAt() *KeywordUpsertOne {
	return u.Update(func(s *KeywordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *KeywordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeywordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeywordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *KeywordUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: KeywordUpsertOne.ID is not supported by MySQL driver. Use KeywordUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *KeywordUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// KeywordCreateBulk is the builder for creating many Keyword entities in bulk.
type KeywordCreateBulk struct {
	config
	err      error
	builders []*KeywordCreate
	conflict []sql.ConflictOption
}

// Save creates the Keyword entities in the database.
func (_c *KeywordCreateBulk) Save(ctx context.Context) ([]*Keyword, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Keyword, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KeywordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KeywordCreateBulk) SaveX(ctx context.Context) []*Keyword {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeywordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeywordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Keyword.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeywordUpsert) {
//			SetText(v+v).
//		}).
//		Exec(ctx)
func (_c *KeywordCreateBulk) OnConflict(opts ...sql.ConflictOption) *KeywordUpsertBulk {
	_c.conflict = opts
	return &KeywordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Keyword.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeywordCreateBulk) OnConflictColumns(columns ...string) *KeywordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeywordUpsertBulk{
		create: _c,
	}
}

// KeywordUpsertBulk is the builder for "upsert"-ing
// a bulk of Keyword nodes.
type KeywordUpsertBulk struct {
	create *KeywordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Keyword.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(keyword.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeywordUpsertBulk) UpdateNewValues() *KeywordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(keyword.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(keyword.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Keyword.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *KeywordUpsertBulk) Ignore() *KeywordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeywordUpsertBulk) DoNothing() *KeywordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeywordCreateBulk.OnConflict
// documentation for more info.
func (u *KeywordUpsertBulk) Update(set func(*KeywordUpsert)) *KeywordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeywordUpsert{UpdateSet: update})
	}))
	return u
}

// SetText sets the "text" field.
func (u *KeywordUpsertBulk) SetText(v string) *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *KeywordUpsertBulk) UpdateText() *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.UpdateText()
	})
}

// SetCategory sets the "category" field.
func (u *KeywordUpsertBulk) SetCategory(v string) *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *KeywordUpsertBulk) UpdateCategory() *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *KeywordUpsertBulk) ClearCategory() *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.ClearCategory()
	})
}

// SetIsActive sets the "is_active" field.
func (u *KeywordUpsertBulk) SetIsActive(v bool) *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *KeywordUpsertBulk) UpdateIsActive() *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KeywordUpsertBulk) SetUpdatedAt(v time.Time) *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KeywordUpsertBulk) UpdateUpdatedAt() *KeywordUpsertBulk {
	return u.Update(func(s *KeywordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *KeywordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the KeywordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeywordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeywordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
