// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"wood-hot-monitor/ent/keywordexpansion"
	"wood-hot-monitor/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KeywordExpansionUpdate is the builder for updating KeywordExpansion entities.
type KeywordExpansionUpdate struct {
	config
	hooks    []Hook
	mutation *KeywordExpansionMutation
}

// Where appends a list predicates to the KeywordExpansionUpdate builder.
func (_u *KeywordExpansionUpdate) Where(ps ...predicate.KeywordExpansion) *KeywordExpansionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKeyword sets the "keyword" field.
func (_u *KeywordExpansionUpdate) SetKeyword(v string) *KeywordExpansionUpdate {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *KeywordExpansionUpdate) SetNillableKeyword(v *string) *KeywordExpansionUpdate {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetExpansion sets the "expansion" field.
func (_u *KeywordExpansionUpdate) SetExpansion(v string) *KeywordExpansionUpdate {
	_u.mutation.SetExpansion(v)
	return _u
}

// SetNillableExpansion sets the "expansion" field if the given value is not nil.
func (_u *KeywordExpansionUpdate) SetNillableExpansion(v *string) *KeywordExpansionUpdate {
	if v != nil {
		_u.SetExpansion(*v)
	}
	return _u
}

// Mutation returns the KeywordExpansionMutation object of the builder.
func (_u *KeywordExpansionUpdate) Mutation() *KeywordExpansionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KeywordExpansionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeywordExpansionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KeywordExpansionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeywordExpansionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KeywordExpansionUpdate) check() error {
	if v, ok := _u.mutation.Keyword(); ok {
		if err := keywordexpansion.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "KeywordExpansion.keyword": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Expansion(); ok {
		if err := keywordexpansion.ExpansionValidator(v); err != nil {
			return &ValidationError{Name: "expansion", err: fmt.Errorf(`ent: validator failed for field "KeywordExpansion.expansion": %w`, err)}
		}
	}
	return nil
}

func (_u *KeywordExpansionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(keywordexpansion.Table, keywordexpansion.Columns, sqlgraph.NewFieldSpec(keywordexpansion.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(keywordexpansion.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expansion(); ok {
		_spec.SetField(keywordexpansion.FieldExpansion, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keywordexpansion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KeywordExpansionUpdateOne is the builder for updating a single KeywordExpansion entity.
type KeywordExpansionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KeywordExpansionMutation
}

// SetKeyword sets the "keyword" field.
func (_u *KeywordExpansionUpdateOne) SetKeyword(v string) *KeywordExpansionUpdateOne {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *KeywordExpansionUpdateOne) SetNillableKeyword(v *string) *KeywordExpansionUpdateOne {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetExpansion sets the "expansion" field.
func (_u *KeywordExpansionUpdateOne) SetExpansion(v string) *KeywordExpansionUpdateOne {
	_u.mutation.SetExpansion(v)
	return _u
}

// SetNillableExpansion sets the "expansion" field if the given value is not nil.
func (_u *KeywordExpansionUpdateOne) SetNillableExpansion(v *string) *KeywordExpansionUpdateOne {
	if v != nil {
		_u.SetExpansion(*v)
	}
	return _u
}

// Mutation returns the KeywordExpansionMutation object of the builder.
func (_u *KeywordExpansionUpdateOne) Mutation() *KeywordExpansionMutation {
	return _u.mutation
}

// Where appends a list predicates to the KeywordExpansionUpdate builder.
func (_u *KeywordExpansionUpdateOne) Where(ps ...predicate.KeywordExpansion) *KeywordExpansionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KeywordExpansionUpdateOne) Select(field string, fields ...string) *KeywordExpansionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KeywordExpansion entity.
func (_u *KeywordExpansionUpdateOne) Save(ctx context.Context) (*KeywordExpansion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeywordExpansionUpdateOne) SaveX(ctx context.Context) *KeywordExpansion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KeywordExpansionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeywordExpansionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KeywordExpansionUpdateOne) check() error {
	if v, ok := _u.mutation.Keyword(); ok {
		if err := keywordexpansion.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "KeywordExpansion.keyword": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Expansion(); ok {
		if err := keywordexpansion.ExpansionValidator(v); err != nil {
			return &ValidationError{Name: "expansion", err: fmt.Errorf(`ent: validator failed for field "KeywordExpansion.expansion": %w`, err)}
		}
	}
	return nil
}

func (_u *KeywordExpansionUpdateOne) sqlSave(ctx context.Context) (_node *KeywordExpansion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(keywordexpansion.Table, keywordexpansion.Columns, sqlgraph.NewFieldSpec(keywordexpansion.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KeywordExpansion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keywordexpansion.FieldID)
		for _, f := range fields {
			if !keywordexpansion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != keywordexpansion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(keywordexpansion.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expansion(); ok {
		_spec.SetField(keywordexpansion.FieldExpansion, field.TypeString, value)
	}
	_node = &KeywordExpansion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keywordexpansion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
