// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wood-hot-monitor/ent/keywordexpansion"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KeywordExpansionCreate is the builder for creating a KeywordExpansion entity.
type KeywordExpansionCreate struct {
	config
	mutation *KeywordExpansionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKeyword sets the "keyword" field.
func (_c *KeywordExpansionCreate) SetKeyword(v string) *KeywordExpansionCreate {
	_c.mutation.SetKeyword(v)
	return _c
}

// SetExpansion sets the "expansion" field.
func (_c *KeywordExpansionCreate) SetExpansion(v string) *KeywordExpansionCreate {
	_c.mutation.SetExpansion(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *KeywordExpansionCreate) SetCreatedAt(v time.Time) *KeywordExpansionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *KeywordExpansionCreate) SetID(v string) *KeywordExpansionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KeywordExpansionCreate) SetNillableID(v *string) *KeywordExpansionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the KeywordExpansionMutation object of the builder.
func (_c *KeywordExpansionCreate) Mutation() *KeywordExpansionMutation {
	return _c.mutation
}

// Save creates the KeywordExpansion in the database.
func (_c *KeywordExpansionCreate) Save(ctx context.Context) (*KeywordExpansion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KeywordExpansionCreate) SaveX(ctx context.Context) *KeywordExpansion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeywordExpansionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeywordExpansionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KeywordExpansionCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := keywordexpansion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KeywordExpansionCreate) check() error {
	if _, ok := _c.mutation.Keyword(); !ok {
		return &ValidationError{Name: "keyword", err: errors.New(`ent: missing required field "KeywordExpansion.keyword"`)}
	}
	if v, ok := _c.mutation.Keyword(); ok {
		if err := keywordexpansion.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "KeywordExpansion.keyword": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Expansion(); !ok {
		return &ValidationError{Name: "expansion", err: errors.New(`ent: missing required field "KeywordExpansion.expansion"`)}
	}
	if v, ok := _c.mutation.Expansion(); ok {
		if err := keywordexpansion.ExpansionValidator(v); err != nil {
			return &ValidationError{Name: "expansion", err: fmt.Errorf(`ent: validator failed for field "KeywordExpansion.expansion": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KeywordExpansion.created_at"`)}
	}
	return nil
}

func (_c *KeywordExpansionCreate) sqlSave(ctx context.Context) (*KeywordExpansion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected KeywordExpansion.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KeywordExpansionCreate) createSpec() (*KeywordExpansion, *sqlgraph.CreateSpec) {
	var (
		_node = &KeywordExpansion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(keywordexpansion.Table, sqlgraph.NewFieldSpec(keywordexpansion.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Keyword(); ok {
		_spec.SetField(keywordexpansion.FieldKeyword, field.TypeString, value)
		_node.Keyword = value
	}
	if value, ok := _c.mutation.Expansion(); ok {
		_spec.SetField(keywordexpansion.FieldExpansion, field.TypeString, value)
		_node.Expansion = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(keywordexpansion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KeywordExpansion.Create().
//		SetKeyword(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeywordExpansionUpsert) {
//			SetKeyword(v+v).
//		}).
//		Exec(ctx)
func (_c *KeywordExpansionCreate) OnConflict(opts ...sql.ConflictOption) *KeywordExpansionUpsertOne {
	_c.conflict = opts
	return &KeywordExpansionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KeywordExpansion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeywordExpansionCreate) OnConflictColumns(columns ...string) *KeywordExpansionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeywordExpansionUpsertOne{
		create: _c,
	}
}

type (
	// KeywordExpansionUpsertOne is the builder for "upsert"-ing
	//  one KeywordExpansion node.
	KeywordExpansionUpsertOne struct {
		create *KeywordExpansionCreate
	}

	// KeywordExpansionUpsert is the "OnConflict" setter.
	KeywordExpansionUpsert struct {
		*sql.UpdateSet
	}
)

// SetKeyword sets the "keyword" field.
func (u *KeywordExpansionUpsert) SetKeyword(v string) *KeywordExpansionUpsert {
	u.Set(keywordexpansion.FieldKeyword, v)
	return u
}

// UpdateKeyword sets the "keyword" field to the value that was provided on create.
func (u *KeywordExpansionUpsert) UpdateKeyword() *KeywordExpansionUpsert {
	u.SetExcluded(keywordexpansion.FieldKeyword)
	return u
}

// SetExpansion sets the "expansion" field.
func (u *KeywordExpansionUpsert) SetExpansion(v string) *KeywordExpansionUpsert {
	u.Set(keywordexpansion.FieldExpansion, v)
	return u
}

// UpdateExpansion sets the "expansion" field to the value that was provided on create.
func (u *KeywordExpansionUpsert) UpdateExpansion() *KeywordExpansionUpsert {
	u.SetExcluded(keywordexpansion.FieldExpansion)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.KeywordExpansion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(keywordexpansion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeywordExpansionUpsertOne) UpdateNewValues() *KeywordExpansionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(keywordexpansion.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(keywordexpansion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KeywordExpansion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *KeywordExpansionUpsertOne) Ignore() *KeywordExpansionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeywordExpansionUpsertOne) DoNothing() *KeywordExpansionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeywordExpansionCreate.OnConflict
// documentation for more info.
func (u *KeywordExpansionUpsertOne) Update(set func(*KeywordExpansionUpsert)) *KeywordExpansionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeywordExpansionUpsert{UpdateSet: update})
	}))
	return u
}

// SetKeyword sets the "keyword" field.
func (u *KeywordExpansionUpsertOne) SetKeyword(v string) *KeywordExpansionUpsertOne {
	return u.Update(func(s *KeywordExpansionUpsert) {
		s.SetKeyword(v)
	})
}

// UpdateKeyword sets the "keyword" field to the value that was provided on create.
func (u *KeywordExpansionUpsertOne) UpdateKeyword() *KeywordExpansionUpsertOne {
	return u.Update(func(s *KeywordExpansionUpsert) {
		s.UpdateKeyword()
	})
}

// SetExpansion sets the "expansion" field.
func (u *KeywordExpansionUpsertOne) SetExpansion(v string) *KeywordExpansionUpsertOne {
	return u.Update(func(s *KeywordExpansionUpsert) {
		s.SetExpansion(v)
	})
}

// UpdateExpansion sets the "expansion" field to the value that was provided on create.
func (u *KeywordExpansionUpsertOne) UpdateExpansion() *KeywordExpansionUpsertOne {
	return u.Update(func(s *KeywordExpansionUpsert) {
		s.UpdateExpansion()
	})
}

// Exec executes the query.
func (u *KeywordExpansionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeywordExpansionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeywordExpansionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *KeywordExpansionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: KeywordExpansionUpsertOne.ID is not supported by MySQL driver. Use KeywordExpansionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *KeywordExpansionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// KeywordExpansionCreateBulk is the builder for creating many KeywordExpansion entities in bulk.
type KeywordExpansionCreateBulk struct {
	config
	err      error
	builders []*KeywordExpansionCreate
	conflict []sql.ConflictOption
}

// Save creates the KeywordExpansion entities in the database.
func (_c *KeywordExpansionCreateBulk) Save(ctx context.Context) ([]*KeywordExpansion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KeywordExpansion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KeywordExpansionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KeywordExpansionCreateBulk) SaveX(ctx context.Context) []*KeywordExpansion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeywordExpansionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeywordExpansionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KeywordExpansion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeywordExpansionUpsert) {
//			SetKeyword(v+v).
//		}).
//		Exec(ctx)
func (_c *KeywordExpansionCreateBulk) OnConflict(opts ...sql.ConflictOption) *KeywordExpansionUpsertBulk {
	_c.conflict = opts
	return &KeywordExpansionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KeywordExpansion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeywordExpansionCreateBulk) OnConflictColumns(columns ...string) *KeywordExpansionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeywordExpansionUpsertBulk{
		create: _c,
	}
}

// KeywordExpansionUpsertBulk is the builder for "upsert"-ing
// a bulk of KeywordExpansion nodes.
type KeywordExpansionUpsertBulk struct {
	create *KeywordExpansionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.KeywordExpansion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(keywordexpansion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeywordExpansionUpsertBulk) UpdateNewValues() *KeywordExpansionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(keywordexpansion.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(keywordexpansion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KeywordExpansion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *KeywordExpansionUpsertBulk) Ignore() *KeywordExpansionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeywordExpansionUpsertBulk) DoNothing() *KeywordExpansionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeywordExpansionCreateBulk.OnConflict
// documentation for more info.
func (u *KeywordExpansionUpsertBulk) Update(set func(*KeywordExpansionUpsert)) *KeywordExpansionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeywordExpansionUpsert{UpdateSet: update})
	}))
	return u
}

// SetKeyword sets the "keyword" field.
func (u *KeywordExpansionUpsertBulk) SetKeyword(v string) *KeywordExpansionUpsertBulk {
	return u.Update(func(s *KeywordExpansionUpsert) {
		s.SetKeyword(v)
	})
}

// UpdateKeyword sets the "keyword" field to the value that was provided on create.
func (u *KeywordExpansionUpsertBulk) UpdateKeyword() *KeywordExpansionUpsertBulk {
	return u.Update(func(s *KeywordExpansionUpsert) {
		s.UpdateKeyword()
	})
}

// SetExpansion sets the "expansion" field.
func (u *KeywordExpansionUpsertBulk) SetExpansion(v string) *KeywordExpansionUpsertBulk {
	return u.Update(func(s *KeywordExpansionUpsert) {
		s.SetExpansion(v)
	})
}

// UpdateExpansion sets the "expansion" field to the value that was provided on create.
func (u *KeywordExpansionUpsertBulk) UpdateExpansion() *KeywordExpansionUpsertBulk {
	return u.Update(func(s *KeywordExpansionUpsert) {
		s.UpdateExpansion()
	})
}

// Exec executes the query.
func (u *KeywordExpansionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the KeywordExpansionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeywordExpansionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeywordExpansionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
