// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"wood-hot-monitor/ent/keywordexpansion"
	"wood-hot-monitor/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KeywordExpansionQuery is the builder for querying KeywordExpansion entities.
type KeywordExpansionQuery struct {
	config
	ctx        *QueryContext
	order      []keywordexpansion.OrderOption
	inters     []Interceptor
	predicates []predicate.KeywordExpansion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the KeywordExpansionQuery builder.
func (_q *KeywordExpansionQuery) Where(ps ...predicate.KeywordExpansion) *KeywordExpansionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *KeywordExpansionQuery) Limit(limit int) *KeywordExpansionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *KeywordExpansionQuery) Offset(offset int) *KeywordExpansionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *KeywordExpansionQuery) Unique(unique bool) *KeywordExpansionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *KeywordExpansionQuery) Order(o ...keywordexpansion.OrderOption) *KeywordExpansionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first KeywordExpansion entity from the query.
// Returns a *NotFoundError when no KeywordExpansion was found.
func (_q *KeywordExpansionQuery) First(ctx context.Context) (*KeywordExpansion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{keywordexpansion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *KeywordExpansionQuery) FirstX(ctx context.Context) *KeywordExpansion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first KeywordExpansion ID from the query.
// Returns a *NotFoundError when no KeywordExpansion ID was found.
func (_q *KeywordExpansionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{keywordexpansion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *KeywordExpansionQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single KeywordExpansion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one KeywordExpansion entity is found.
// Returns a *NotFoundError when no KeywordExpansion entities are found.
func (_q *KeywordExpansionQuery) Only(ctx context.Context) (*KeywordExpansion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{keywordexpansion.Label}
	default:
		return nil, &NotSingularError{keywordexpansion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *KeywordExpansionQuery) OnlyX(ctx context.Context) *KeywordExpansion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only KeywordExpansion ID in the query.
// Returns a *NotSingularError when more than one KeywordExpansion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *KeywordExpansionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{keywordexpansion.Label}
	default:
		err = &NotSingularError{keywordexpansion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *KeywordExpansionQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of KeywordExpansions.
func (_q *KeywordExpansionQuery) All(ctx context.Context) ([]*KeywordExpansion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*KeywordExpansion, *KeywordExpansionQuery]()
	return withInterceptors[[]*KeywordExpansion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *KeywordExpansionQuery) AllX(ctx context.Context) []*KeywordExpansion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of KeywordExpansion IDs.
func (_q *KeywordExpansionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(keywordexpansion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *KeywordExpansionQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *KeywordExpansionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*KeywordExpansionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *KeywordExpansionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *KeywordExpansionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *KeywordExpansionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the KeywordExpansionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *KeywordExpansionQuery) Clone() *KeywordExpansionQuery {
	if _q == nil {
		return nil
	}
	return &KeywordExpansionQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]keywordexpansion.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.KeywordExpansion{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Keyword string `json:"keyword,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.KeywordExpansion.Query().
//		GroupBy(keywordexpansion.FieldKeyword).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *KeywordExpansionQuery) GroupBy(field string, fields ...string) *KeywordExpansionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &KeywordExpansionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = keywordexpansion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Keyword string `json:"keyword,omitempty"`
//	}
//
//	client.KeywordExpansion.Query().
//		Select(keywordexpansion.FieldKeyword).
//		Scan(ctx, &v)
func (_q *KeywordExpansionQuery) Select(fields ...string) *KeywordExpansionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &KeywordExpansionSelect{KeywordExpansionQuery: _q}
	sbuild.label = keywordexpansion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a KeywordExpansionSelect configured with the given aggregations.
func (_q *KeywordExpansionQuery) Aggregate(fns ...AggregateFunc) *KeywordExpansionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *KeywordExpansionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !keywordexpansion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *KeywordExpansionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*KeywordExpansion, error) {
	var (
		nodes = []*KeywordExpansion{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*KeywordExpansion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &KeywordExpansion{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *KeywordExpansionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *KeywordExpansionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(keywordexpansion.Table, keywordexpansion.Columns, sqlgraph.NewFieldSpec(keywordexpansion.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keywordexpansion.FieldID)
		for i := range fields {
			if fields[i] != keywordexpansion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *KeywordExpansionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(keywordexpansion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = keywordexpansion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// KeywordExpansionGroupBy is the group-by builder for KeywordExpansion entities.
type KeywordExpansionGroupBy struct {
	selector
	build *KeywordExpansionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *KeywordExpansionGroupBy) Aggregate(fns ...AggregateFunc) *KeywordExpansionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *KeywordExpansionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*KeywordExpansionQuery, *KeywordExpansionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *KeywordExpansionGroupBy) sqlScan(ctx context.Context, root *KeywordExpansionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// KeywordExpansionSelect is the builder for selecting fields of KeywordExpansion entities.
type KeywordExpansionSelect struct {
	*KeywordExpansionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *KeywordExpansionSelect) Aggregate(fns ...AggregateFunc) *KeywordExpansionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *KeywordExpansionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*KeywordExpansionQuery, *KeywordExpansionSelect](ctx, _s.KeywordExpansionQuery, _s, _s.inters, v)
}

func (_s *KeywordExpansionSelect) sqlScan(ctx context.Context, root *KeywordExpansionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
