// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wood-hot-monitor/ent/hotspot"
	"wood-hot-monitor/ent/keyword"
	"wood-hot-monitor/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KeywordUpdate is the builder for updating Keyword entities.
type KeywordUpdate struct {
	config
	hooks    []Hook
	mutation *KeywordMutation
}

// Where appends a list predicates to the KeywordUpdate builder.
func (_u *KeywordUpdate) Where(ps ...predicate.Keyword) *KeywordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *KeywordUpdate) SetText(v string) *KeywordUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *KeywordUpdate) SetNillableText(v *string) *KeywordUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *KeywordUpdate) SetCategory(v string) *KeywordUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *KeywordUpdate) SetNillableCategory(v *string) *KeywordUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *KeywordUpdate) ClearCategory() *KeywordUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *KeywordUpdate) SetIsActive(v bool) *KeywordUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *KeywordUpdate) SetNillableIsActive(v *bool) *KeywordUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KeywordUpdate) SetUpdatedAt(v time.Time) *KeywordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *KeywordUpdate) SetNillableUpdatedAt(v *time.Time) *KeywordUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddHotspotIDs adds the "hotspots" edge to the Hotspot entity by IDs.
func (_u *KeywordUpdate) AddHotspotIDs(ids ...string) *KeywordUpdate {
	_u.mutation.AddHotspotIDs(ids...)
	return _u
}

// AddHotspots adds the "hotspots" edges to the Hotspot entity.
func (_u *KeywordUpdate) AddHotspots(v ...*Hotspot) *KeywordUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHotspotIDs(ids...)
}

// Mutation returns the KeywordMutation object of the builder.
func (_u *KeywordUpdate) Mutation() *KeywordMutation {
	return _u.mutation
}

// ClearHotspots clears all "hotspots" edges to the Hotspot entity.
func (_u *KeywordUpdate) ClearHotspots() *KeywordUpdate {
	_u.mutation.ClearHotspots()
	return _u
}

// RemoveHotspotIDs removes the "hotspots" edge to Hotspot entities by IDs.
func (_u *KeywordUpdate) RemoveHotspotIDs(ids ...string) *KeywordUpdate {
	_u.mutation.RemoveHotspotIDs(ids...)
	return _u
}

// RemoveHotspots removes "hotspots" edges to Hotspot entities.
func (_u *KeywordUpdate) RemoveHotspots(v ...*Hotspot) *KeywordUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHotspotIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KeywordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeywordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KeywordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeywordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KeywordUpdate) check() error {
	if v, ok := _u.mutation.Text(); ok {
		if err := keyword.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Keyword.text": %w`, err)}
		}
	}
	return nil
}

func (_u *KeywordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(keyword.Table, keyword.Columns, sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(keyword.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(keyword.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(keyword.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(keyword.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(keyword.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.HotspotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyword.HotspotsTable,
			Columns: []string{keyword.HotspotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotspot.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHotspotsIDs(); len(nodes) > 0 && !_u.mutation.HotspotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyword.HotspotsTable,
			Columns: []string{keyword.HotspotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotspot.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HotspotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyword.HotspotsTable,
			Columns: []string{keyword.HotspotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotspot.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keyword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KeywordUpdateOne is the builder for updating a single Keyword entity.
type KeywordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KeywordMutation
}

// SetText sets the "text" field.
func (_u *KeywordUpdateOne) SetText(v string) *KeywordUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *KeywordUpdateOne) SetNillableText(v *string) *KeywordUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *KeywordUpdateOne) SetCategory(v string) *KeywordUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *KeywordUpdateOne) SetNillableCategory(v *string) *KeywordUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *KeywordUpdateOne) ClearCategory() *KeywordUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *KeywordUpdateOne) SetIsActive(v bool) *KeywordUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *KeywordUpdateOne) SetNillableIsActive(v *bool) *KeywordUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KeywordUpdateOne) SetUpdatedAt(v time.Time) *KeywordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *KeywordUpdateOne) SetNillableUpdatedAt(v *time.Time) *KeywordUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddHotspotIDs adds the "hotspots" edge to the Hotspot entity by IDs.
func (_u *KeywordUpdateOne) AddHotspotIDs(ids ...string) *KeywordUpdateOne {
	_u.mutation.AddHotspotIDs(ids...)
	return _u
}

// AddHotspots adds the "hotspots" edges to the Hotspot entity.
func (_u *KeywordUpdateOne) AddHotspots(v ...*Hotspot) *KeywordUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHotspotIDs(ids...)
}

// Mutation returns the KeywordMutation object of the builder.
func (_u *KeywordUpdateOne) Mutation() *KeywordMutation {
	return _u.mutation
}

// ClearHotspots clears all "hotspots" edges to the Hotspot entity.
func (_u *KeywordUpdateOne) ClearHotspots() *KeywordUpdateOne {
	_u.mutation.ClearHotspots()
	return _u
}

// RemoveHotspotIDs removes the "hotspots" edge to Hotspot entities by IDs.
func (_u *KeywordUpdateOne) RemoveHotspotIDs(ids ...string) *KeywordUpdateOne {
	_u.mutation.RemoveHotspotIDs(ids...)
	return _u
}

// RemoveHotspots removes "hotspots" edges to Hotspot entities.
func (_u *KeywordUpdateOne) RemoveHotspots(v ...*Hotspot) *KeywordUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHotspotIDs(ids...)
}

// Where appends a list predicates to the KeywordUpdate builder.
func (_u *KeywordUpdateOne) Where(ps ...predicate.Keyword) *KeywordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KeywordUpdateOne) Select(field string, fields ...string) *KeywordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Keyword entity.
func (_u *KeywordUpdateOne) Save(ctx context.Context) (*Keyword, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeywordUpdateOne) SaveX(ctx context.Context) *Keyword {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KeywordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeywordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KeywordUpdateOne) check() error {
	if v, ok := _u.mutation.Text(); ok {
		if err := keyword.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Keyword.text": %w`, err)}
		}
	}
	return nil
}

func (_u *KeywordUpdateOne) sqlSave(ctx context.Context) (_node *Keyword, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(keyword.Table, keyword.Columns, sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Keyword.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keyword.FieldID)
		for _, f := range fields {
			if !keyword.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != keyword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(keyword.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(keyword.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(keyword.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(keyword.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(keyword.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.HotspotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyword.HotspotsTable,
			Columns: []string{keyword.HotspotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotspot.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHotspotsIDs(); len(nodes) > 0 && !_u.mutation.HotspotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyword.HotspotsTable,
			Columns: []string{keyword.HotspotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotspot.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HotspotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyword.HotspotsTable,
			Columns: []string{keyword.HotspotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotspot.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Keyword{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keyword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
