// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"wood-hot-monitor/ent/keyword"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Keyword is the model entity for the Keyword schema.
type Keyword struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// Category holds the value of the "category" field.
	Category *string `json:"category,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KeywordQuery when eager-loading is set.
	Edges        KeywordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// KeywordEdges holds the relations/edges for other nodes in the graph.
type KeywordEdges struct {
	// Hotspots holds the value of the hotspots edge.
	Hotspots []*Hotspot `json:"hotspots,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HotspotsOrErr returns the Hotspots value or an error if the edge
// was not loaded in eager-loading.
func (e KeywordEdges) HotspotsOrErr() ([]*Hotspot, error) {
	if e.loadedTypes[0] {
		return e.Hotspots, nil
	}
	return nil, &NotLoadedError{edge: "hotspots"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Keyword) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case keyword.FieldIsActive:
			values[i] = new(sql.NullBool)
		case keyword.FieldID, keyword.FieldText, keyword.FieldCategory:
			values[i] = new(sql.NullString)
		case keyword.FieldCreatedAt, keyword.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Keyword fields.
func (_m *Keyword) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case keyword.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case keyword.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case keyword.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = new(string)
				*_m.Category = value.String
			}
		case keyword.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case keyword.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case keyword.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Keyword.
// This includes values selected through modifiers, order, etc.
func (_m *Keyword) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHotspots queries the "hotspots" edge of the Keyword entity.
func (_m *Keyword) QueryHotspots() *HotspotQuery {
	return NewKeywordClient(_m.config).QueryHotspots(_m)
}

// Update returns a builder for updating this Keyword.
// Note that you need to call Keyword.Unwrap() before calling this method if this Keyword
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Keyword) Update() *KeywordUpdateOne {
	return NewKeywordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Keyword entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Keyword) Unwrap() *Keyword {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Keyword is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Keyword) String() string {
	var builder strings.Builder
	builder.WriteString("Keyword(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	if v := _m.Category; v != nil {
		builder.WriteString("category=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Keywords is a parsable slice of Keyword.
type Keywords []*Keyword
