// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"wood-hot-monitor/ent/keywordexpansion"
	"wood-hot-monitor/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KeywordExpansionDelete is the builder for deleting a KeywordExpansion entity.
type KeywordExpansionDelete struct {
	config
	hooks    []Hook
	mutation *KeywordExpansionMutation
}

// Where appends a list predicates to the KeywordExpansionDelete builder.
func (_d *KeywordExpansionDelete) Where(ps ...predicate.KeywordExpansion) *KeywordExpansionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *KeywordExpansionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *KeywordExpansionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *KeywordExpansionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(keywordexpansion.Table, sqlgraph.NewFieldSpec(keywordexpansion.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// KeywordExpansionDeleteOne is the builder for deleting a single KeywordExpansion entity.
type KeywordExpansionDeleteOne struct {
	_d *KeywordExpansionDelete
}

// Where appends a list predicates to the KeywordExpansionDelete builder.
func (_d *KeywordExpansionDeleteOne) Where(ps ...predicate.KeywordExpansion) *KeywordExpansionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *KeywordExpansionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{keywordexpansion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *KeywordExpansionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
