// +build tools
// +build tools
// Code generated by ent, DO NOT EDIT.

package ent

import (
	enthotspot "wood-hot-monitor/ent/hotspot"
	"wood-hot-monitor/ent/keyword"
	"wood-hot-monitor/ent/keywordexpansion"
	"wood-hot-monitor/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	enthotspotFields := schema.Hotspot{}.Fields()
	_ = enthotspotFields
	// enthotspotDescIsReal is the schema descriptor for is_real field.
	enthotspotDescIsReal := enthotspotFields[6].Descriptor()
	// enthotspot.DefaultIsReal holds the default value on creation for the is_real field.
	enthotspot.DefaultIsReal = enthotspotDescIsReal.Default.(bool)
	// enthotspotDescRelevance is the schema descriptor for relevance field.
	enthotspotDescRelevance := enthotspotFields[7].Descriptor()
	// enthotspot.DefaultRelevance holds the default value on creation for the relevance field.
	enthotspot.DefaultRelevance = enthotspotDescRelevance.Default.(int)
	// enthotspotDescIsNotified is the schema descriptor for is_notified field.
	enthotspotDescIsNotified := enthotspotFields[27].Descriptor()
	// enthotspot.DefaultIsNotified holds the default value on creation for the is_notified field.
	enthotspot.DefaultIsNotified = enthotspotDescIsNotified.Default.(bool)
	// enthotspotDescIsRead is the schema descriptor for is_read field.
	enthotspotDescIsRead := enthotspotFields[29].Descriptor()
	// enthotspot.DefaultIsRead holds the default value on creation for the is_read field.
	enthotspot.DefaultIsRead = enthotspotDescIsRead.Default.(bool)
	// enthotspotDescID is the schema descriptor for id field.
	enthotspotDescID := enthotspotFields[0].Descriptor()
	// enthotspot.DefaultID holds the default value on creation for the id field.
	enthotspot.DefaultID = enthotspotDescID.Default.(func() string)
	keywordFields := schema.Keyword{}.Fields()
	_ = keywordFields
	// keywordDescText is the schema descriptor for text field.
	keywordDescText := keywordFields[1].Descriptor()
	// keyword.TextValidator is a validator for the "text" field. It is called by the builders before save.
	keyword.TextValidator = keywordDescText.Validators[0].(func(string) error)
	// keywordDescIsActive is the schema descriptor for is_active field.
	keywordDescIsActive := keywordFields[3].Descriptor()
	// keyword.DefaultIsActive holds the default value on creation for the is_active field.
	keyword.DefaultIsActive = keywordDescIsActive.Default.(bool)
	// keywordDescID is the schema descriptor for id field.
	keywordDescID := keywordFields[0].Descriptor()
	// keyword.DefaultID holds the default value on creation for the id field.
	keyword.DefaultID = keywordDescID.Default.(func() string)
	keywordexpansionFields := schema.KeywordExpansion{}.Fields()
	_ = keywordexpansionFields
	// keywordexpansionDescKeyword is the schema descriptor for keyword field.
	keywordexpansionDescKeyword := keywordexpansionFields[1].Descriptor()
	// keywordexpansion.KeywordValidator is a validator for the "keyword" field. It is called by the builders before save.
	keywordexpansion.KeywordValidator = keywordexpansionDescKeyword.Validators[0].(func(string) error)
	// keywordexpansionDescExpansion is the schema descriptor for expansion field.
	keywordexpansionDescExpansion := keywordexpansionFields[2].Descriptor()
	// keywordexpansion.ExpansionValidator is a validator for the "expansion" field. It is called by the builders before save.
	keywordexpansion.ExpansionValidator = keywordexpansionDescExpansion.Validators[0].(func(string) error)
	// keywordexpansionDescID is the schema descriptor for id field.
	keywordexpansionDescID := keywordexpansionFields[0].Descriptor()
	// keywordexpansion.DefaultID holds the default value on creation for the id field.
	keywordexpansion.DefaultID = keywordexpansionDescID.Default.(func() string)
}
