// Code generated by ent, DO NOT EDIT.

package ent

import (
	"wood-hot-monitor/ent/hotspot"
	"wood-hot-monitor/ent/keyword"
	"wood-hot-monitor/ent/keywordexpansion"
	"wood-hot-monitor/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hotspotFields := schema.Hotspot{}.Fields()
	_ = hotspotFields
	// hotspotDescIsReal is the schema descriptor for is_real field.
	hotspotDescIsReal := hotspotFields[6].Descriptor()
	// hotspot.DefaultIsReal holds the default value on creation for the is_real field.
	hotspot.DefaultIsReal = hotspotDescIsReal.Default.(bool)
	// hotspotDescRelevance is the schema descriptor for relevance field.
	hotspotDescRelevance := hotspotFields[7].Descriptor()
	// hotspot.DefaultRelevance holds the default value on creation for the relevance field.
	hotspot.DefaultRelevance = hotspotDescRelevance.Default.(int)
	// hotspotDescImportance is the schema descriptor for importance field.
	hotspotDescImportance := hotspotFields[10].Descriptor()
	// hotspot.DefaultImportance holds the default value on creation for the importance field.
	hotspot.DefaultImportance = hotspotDescImportance.Default.(string)
	// hotspotDescIsNotified is the schema descriptor for is_notified field.
	hotspotDescIsNotified := hotspotFields[27].Descriptor()
	// hotspot.DefaultIsNotified holds the default value on creation for the is_notified field.
	hotspot.DefaultIsNotified = hotspotDescIsNotified.Default.(bool)
	// hotspotDescIsRead is the schema descriptor for is_read field.
	hotspotDescIsRead := hotspotFields[29].Descriptor()
	// hotspot.DefaultIsRead holds the default value on creation for the is_read field.
	hotspot.DefaultIsRead = hotspotDescIsRead.Default.(bool)
	// hotspotDescID is the schema descriptor for id field.
	hotspotDescID := hotspotFields[0].Descriptor()
	// hotspot.DefaultID holds the default value on creation for the id field.
	hotspot.DefaultID = hotspotDescID.Default.(func() string)
	keywordFields := schema.Keyword{}.Fields()
	_ = keywordFields
	// keywordDescText is the schema descriptor for text field.
	keywordDescText := keywordFields[1].Descriptor()
	// keyword.TextValidator is a validator for the "text" field. It is called by the builders before save.
	keyword.TextValidator = keywordDescText.Validators[0].(func(string) error)
	// keywordDescIsActive is the schema descriptor for is_active field.
	keywordDescIsActive := keywordFields[3].Descriptor()
	// keyword.DefaultIsActive holds the default value on creation for the is_active field.
	keyword.DefaultIsActive = keywordDescIsActive.Default.(bool)
	// keywordDescID is the schema descriptor for id field.
	keywordDescID := keywordFields[0].Descriptor()
	// keyword.DefaultID holds the default value on creation for the id field.
	keyword.DefaultID = keywordDescID.Default.(func() string)
	keywordexpansionFields := schema.KeywordExpansion{}.Fields()
	_ = keywordexpansionFields
	// keywordexpansionDescKeyword is the schema descriptor for keyword field.
	keywordexpansionDescKeyword := keywordexpansionFields[1].Descriptor()
	// keywordexpansion.KeywordValidator is a validator for the "keyword" field. It is called by the builders before save.
	keywordexpansion.KeywordValidator = keywordexpansionDescKeyword.Validators[0].(func(string) error)
	// keywordexpansionDescExpansion is the schema descriptor for expansion field.
	keywordexpansionDescExpansion := keywordexpansionFields[2].Descriptor()
	// keywordexpansion.ExpansionValidator is a validator for the "expansion" field. It is called by the builders before save.
	keywordexpansion.ExpansionValidator = keywordexpansionDescExpansion.Validators[0].(func(string) error)
	// keywordexpansionDescID is the schema descriptor for id field.
	keywordexpansionDescID := keywordexpansionFields[0].Descriptor()
	// keywordexpansion.DefaultID holds the default value on creation for the id field.
	keywordexpansion.DefaultID = keywordexpansionDescID.Default.(func() string)
}
