/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const SettingsLazyRouteImport = createFileRoute('/settings')()
const SearchLazyRouteImport = createFileRoute('/search')()
const ManageLazyRouteImport = createFileRoute('/manage')()
const KeywordsLazyRouteImport = createFileRoute('/keywords')()
const IndexLazyRouteImport = createFileRoute('/')()

const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const SearchLazyRoute = SearchLazyRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))
const ManageLazyRoute = ManageLazyRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/manage.lazy').then((d) => d.Route))
const KeywordsLazyRoute = KeywordsLazyRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/keywords.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/keywords': typeof KeywordsLazyRoute
  '/manage': typeof ManageLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/keywords': typeof KeywordsLazyRoute
  '/manage': typeof ManageLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/keywords': typeof KeywordsLazyRoute
  '/manage': typeof ManageLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/keywords' | '/manage' | '/search' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/keywords' | '/manage' | '/search' | '/settings'
  id: '__root__' | '/' | '/keywords' | '/manage' | '/search' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  KeywordsLazyRoute: typeof KeywordsLazyRoute
  ManageLazyRoute: typeof ManageLazyRoute
  SearchLazyRoute: typeof SearchLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  KeywordsLazyRoute: KeywordsLazyRoute,
  ManageLazyRoute: ManageLazyRoute,
  SearchLazyRoute: SearchLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
